create or replace function public.is_approved_staff()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.staff_profiles where id = auth.uid() and status = 'Approved') $$;
revoke all on function public.is_approved_staff() from public;
grant execute on function public.is_approved_staff() to authenticated;

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null, email text not null default '', phone text not null default '', address text not null default '',
  company_name text not null default '', site_address text not null default '', notes text not null default '',
  archived boolean not null default false, created_at timestamptz not null default now()
);
create table if not exists public.team_members (
  id bigint generated by default as identity primary key, name text not null, email text not null default '', phone text not null default '',
  role text not null default 'Salesperson', active boolean not null default true, created_at timestamptz not null default now()
);
create table if not exists public.product_catalog (
  id bigint generated by default as identity primary key, name text not null, category text not null, price numeric(12,2) not null default 0,
  effective_from date, active boolean not null default true, created_at timestamptz not null default now(), unique(name, category)
);
create table if not exists public.company_settings (
  id bigint primary key default 1, company_name text not null default 'RobeFlow Wardrobes', subtitle text not null default 'Custom wardrobe solutions',
  gst_number text not null default '', phone text not null default '', email text not null default '', address text not null default 'Christchurch, New Zealand',
  bank_details text not null default '', default_validity_days integer not null default 30, deposit_percent numeric(5,2) not null default 40,
  terms text not null default 'Prices are in New Zealand dollars and include GST.', warranty text not null default '',
  installation_exclusions text not null default '', email_signature text not null default 'Kind regards\nRobeFlow Wardrobes'
);
create table if not exists public.quotes (
  id bigint generated by default as identity primary key, quote_number text not null unique, customer_id bigint references public.customers(id),
  customer_name text not null, project text not null, company_name text not null default '', email text not null default '', phone text not null default '',
  customer_address text not null default '', site_address text not null default '', service_type text not null default 'Pick Up', service_price numeric(12,2) not null default 0,
  salesperson_name text not null default '', amount numeric(12,2) not null default 0, status text not null default 'Draft',
  invoice_number text not null default '', invoice_status text not null default 'To invoice', payment_note text not null default '',
  invoice_sent_at timestamptz, emailed_at timestamptz, email_id text, valid_until date not null, created_at timestamptz not null default now(),
  revision integer not null default 1, parent_quote_id bigint references public.quotes(id), follow_up_date date, purchase_order_number text not null default '',
  acceptance_token uuid not null default gen_random_uuid(), accepted_at timestamptz, customer_comment text not null default '',
  job_stage text not null default 'Awaiting acceptance', accounts_approved boolean not null default false,
  dispatch_status text not null default 'Awaiting dispatch', tracking_number text not null default '', tracking_sent_at timestamptz,
  pick_list_status text not null default 'Not generated', picked_by text not null default '', picked_at timestamptz,
  discount_percent numeric(5,2) not null default 0, archived boolean not null default false
);
create table if not exists public.quote_items (
  id bigint generated by default as identity primary key, quote_id bigint not null references public.quotes(id) on delete cascade,
  category text not null, system_type text not null default 'I-Robe', colour text not null default 'Undecided', design_selection text not null default 'Custom design',
  hardware_colour text not null default 'Undecided', door_configuration text not null default '', mirror_option text not null default '',
  price numeric(12,2) not null default 0, quantity numeric(10,2) not null default 1, unit_price numeric(12,2) not null default 0,
  description text not null default '', sort_order integer not null default 0
);
create table if not exists public.quote_activities (
  id bigint generated by default as identity primary key, quote_id bigint not null references public.quotes(id) on delete cascade,
  action text not null, detail text not null default '', actor text not null default 'RobeFlow', created_at timestamptz not null default now()
);
create table if not exists public.payment_transactions (
  id bigint generated by default as identity primary key, quote_id bigint not null references public.quotes(id) on delete cascade,
  amount numeric(12,2) not null, payment_date date not null, method text not null default 'Bank transfer', reference text not null default '',
  notes text not null default '', recorded_by text not null default 'RobeFlow', created_at timestamptz not null default now()
);

alter table public.customers enable row level security;
alter table public.team_members enable row level security;
alter table public.product_catalog enable row level security;
alter table public.company_settings enable row level security;
alter table public.quotes enable row level security;
alter table public.quote_items enable row level security;
alter table public.quote_activities enable row level security;
alter table public.payment_transactions enable row level security;

do $$ declare table_name text; begin
  foreach table_name in array array['customers','team_members','product_catalog','company_settings','quotes','quote_items','quote_activities','payment_transactions'] loop
    execute format('drop policy if exists staff_access on public.%I', table_name);
    execute format('create policy staff_access on public.%I for all to authenticated using (public.is_approved_staff()) with check (public.is_approved_staff())', table_name);
    execute format('grant select, insert, update, delete on public.%I to authenticated', table_name);
  end loop;
end $$;
grant usage, select on all sequences in schema public to authenticated;
insert into public.company_settings(id) values (1) on conflict (id) do nothing;
notify pgrst, 'reload schema';
