create table if not exists public.quote_attachments (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references public.quotes(id) on delete cascade,
  file_name text not null, content_type text not null default 'application/octet-stream', size bigint not null default 0,
  object_key text not null unique, created_at timestamptz not null default now()
);
create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  name text not null, company_name text not null default '', email text not null, phone text not null default '',
  address text not null default '', site_address text not null default '', project_type text not null default 'Wardrobes',
  areas text not null default '', preferred_colour text not null default '', timeframe text not null default '', notes text not null default '',
  status text not null default 'New', salesperson_name text not null default '', created_at timestamptz not null default now()
);
create table if not exists public.enquiry_attachments (
  id bigint generated by default as identity primary key,
  enquiry_id bigint not null references public.enquiries(id) on delete cascade,
  file_name text not null, content_type text not null default 'application/octet-stream', size bigint not null default 0,
  object_key text not null unique, created_at timestamptz not null default now()
);
create table if not exists public.job_schedule_events (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references public.quotes(id) on delete cascade,
  event_type text not null check (event_type in ('Site measure','Installation')),
  scheduled_date date not null, start_time time not null, end_time time not null,
  assigned_to text not null default '', notes text not null default '', status text not null default 'Scheduled',
  created_at timestamptz not null default now()
);
create table if not exists public.pick_list_items (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references public.quotes(id) on delete cascade,
  area_name text not null default '', product_name text not null, sku text not null default '',
  quantity numeric(12,2) not null default 0, unit_cost numeric(12,2) not null default 0,
  checked boolean not null default false, notes text not null default '', sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
create table if not exists public.email_deliveries (
  id bigint generated by default as identity primary key,
  quote_id bigint references public.quotes(id) on delete cascade, kind text not null,
  recipient text not null, provider_id text, status text not null default 'Sent', error text,
  created_at timestamptz not null default now(), unique(kind, quote_id, recipient, provider_id)
);

do $$ declare table_name text; begin
  foreach table_name in array array['quote_attachments','enquiries','enquiry_attachments','job_schedule_events','pick_list_items','email_deliveries'] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists staff_access on public.%I', table_name);
    execute format('create policy staff_access on public.%I for all to authenticated using (public.is_approved_staff()) with check (public.is_approved_staff())', table_name);
    execute format('grant select, insert, update, delete on public.%I to authenticated', table_name);
  end loop;
end $$;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('robeflow-files','robeflow-files',false,15728640,array['application/pdf','image/jpeg','image/png','image/webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'])
on conflict (id) do update set file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists robeflow_staff_files on storage.objects;
create policy robeflow_staff_files on storage.objects for all to authenticated
using (bucket_id='robeflow-files' and public.is_approved_staff())
with check (bucket_id='robeflow-files' and public.is_approved_staff());
notify pgrst, 'reload schema';
