"use client";
import { useEffect,useState } from "react";
import { ArrowLeft,CheckCircle2,Download,FileSpreadsheet,History,Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Job={id:number;quoteNumber:string;customerName:string;companyName:string;project:string;siteAddress:string;serviceType:string;salespersonName:string;pickListStatus:string};
type Document={id:number;version:number;fileName:string;size:number;source:"Generated"|"Uploaded";uploadedBy:string;isCurrent:boolean;createdAt:string};

export default function PickListWorkbook({params}:{params:Promise<{id:string}>}){
 const[id,setId]=useState(0),[job,setJob]=useState<Job|null>(null),[documents,setDocuments]=useState<Document[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function load(jobId=id){const[jobResponse,documentResponse]=await Promise.all([fetch(`/api/pick-list/${jobId}`),fetch(`/api/pick-list/${jobId}/documents`)]);const jobData=await jobResponse.json(),documentData=await documentResponse.json();if(!jobResponse.ok){setError(jobData.error||"This job could not be opened.");return}if(!documentResponse.ok){setError(documentData.error||"Pick-list documents could not be loaded.");return}setJob(jobData.job);setDocuments(documentData.documents??[])}
 useEffect(()=>{params.then(value=>{const jobId=Number(value.id);setId(jobId);load(jobId)})},[params]);
 async function upload(files:FileList|null){const file=files?.[0];if(!file)return;setBusy(true);try{const form=new FormData();form.append("file",file);const response=await fetch(`/api/pick-list/${id}/documents`,{method:"POST",body:form}),data=await response.json();if(!response.ok){window.alert(data.error||"The workbook could not be uploaded.");return}await load()}finally{setBusy(false)}}
 if(error)return <main className="grid min-h-screen place-items-center p-6"><section className="max-w-lg rounded-2xl border bg-white p-8 shadow-sm"><h1 className="text-xl font-bold">Unable to open Excel pick list</h1><p className="mt-2 text-slate-600">{error}</p><Button className="mt-5" variant="outline" onClick={()=>history.back()}><ArrowLeft/>Back</Button></section></main>;
 if(!job)return <main className="grid min-h-screen place-items-center">Loading Excel pick list…</main>;
 const current=documents.find(file=>file.isCurrent);
 return <main className="min-h-screen bg-slate-100 p-4 sm:p-8"><div className="mx-auto max-w-5xl space-y-5">
  <header className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><p className="text-xs font-black uppercase tracking-[.2em] text-emerald-700">RobeFlow Wardrobes</p><h1 className="mt-1 text-2xl font-black">Excel pick list</h1><p className="mt-2 text-slate-500">{job.quoteNumber} · {job.customerName} · {job.project}</p></div><Button variant="outline" onClick={()=>history.back()}><ArrowLeft/>Back</Button></div><div className="mt-5 grid gap-3 rounded-xl bg-slate-50 p-4 text-sm sm:grid-cols-4"><Info label="Salesperson" value={job.salespersonName}/><Info label="Service" value={job.serviceType}/><Info label="Site" value={job.siteAddress||"Not recorded"}/><Info label="Status" value={job.pickListStatus||"Not created"}/></div></header>
  <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-emerald-100 text-emerald-800"><FileSpreadsheet/></span><div><h2 className="text-lg font-bold">Internal Excel pick list</h2><p className="mt-1 text-sm leading-6 text-slate-600">The salesperson completes this workbook manually in Excel. Dispatch can download the current file, edit it in Excel, and upload the revised file below. It is never included in customer emails.</p></div></div></section>
  <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-start gap-4"><span className="grid size-12 shrink-0 place-items-center rounded-xl bg-amber-100 text-amber-800"><Upload/></span><div><h2 className="text-lg font-bold">Upload or replace the pick list</h2><p className="mt-1 text-sm leading-6 text-slate-600">Upload the manually completed Excel workbook. Each replacement becomes the current Dispatch copy and the earlier version remains available below.</p></div></div><label className={`mt-5 inline-flex h-10 cursor-pointer items-center gap-2 rounded-md bg-slate-900 px-4 text-sm font-semibold text-white ${busy?"pointer-events-none opacity-50":""}`}><Upload className="size-4"/>{busy?"Uploading…":current?"Upload revised Excel file":"Choose Excel pick list"}<Input className="hidden" type="file" accept=".xlsm,.xlsx,.xls" onChange={event=>upload(event.target.files)}/></label></section>
  {current&&<section className="rounded-2xl border border-emerald-300 bg-emerald-50 p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex min-w-0 items-start gap-3"><CheckCircle2 className="mt-0.5 shrink-0 text-emerald-700"/><div className="min-w-0"><p className="font-bold text-emerald-950">Current pick list for Dispatch</p><p className="truncate text-sm text-emerald-800">Version {current.version} · {current.fileName}</p><p className="mt-1 text-xs text-emerald-700">{current.source} by {current.uploadedBy} · {new Date(current.createdAt).toLocaleString("en-NZ")}</p></div></div><a className="inline-flex h-10 shrink-0 items-center justify-center gap-2 rounded-md bg-emerald-700 px-4 text-sm font-semibold text-white" href={`/api/pick-list/documents/${current.id}`}><Download className="size-4"/>Download current</a></div></section>}
  <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex items-center gap-2 border-b bg-slate-50 px-5 py-4"><History className="size-5 text-emerald-700"/><div><h2 className="font-bold">Workbook history</h2><p className="text-xs text-slate-500">Every uploaded version is retained.</p></div></div>{documents.length?<div className="divide-y">{documents.map(file=><div key={file.id} className="flex flex-col justify-between gap-3 px-5 py-4 sm:flex-row sm:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><strong>Version {file.version}</strong>{file.isCurrent&&<span className="rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-bold text-emerald-800">Current</span>}<span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-semibold">{file.source}</span></div><p className="mt-1 truncate text-sm">{file.fileName}</p><p className="mt-1 text-xs text-slate-500">{file.uploadedBy} · {new Date(file.createdAt).toLocaleString("en-NZ")} · {(file.size/1024/1024).toFixed(1)} MB</p></div><a className="inline-flex h-9 shrink-0 items-center justify-center gap-2 rounded-md border px-3 text-sm font-medium hover:bg-slate-50" href={`/api/pick-list/documents/${file.id}`}><Download className="size-4"/>Download</a></div>)}</div>:<p className="p-8 text-center text-sm text-slate-500">No Excel pick list has been uploaded yet.</p>}</section>
 </div></main>
}

function Info({label,value}:{label:string;value:string}){return <div><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-semibold">{value||"—"}</p></div>}
