import { desc,eq } from "drizzle-orm";
import { getDb } from "../../../db";
import { productCatalog } from "../../../db/schema";
import { requireAdminApi,requireOwnerApi } from "../../api-auth";

export async function GET(){
 const denied=await requireOwnerApi();if(denied)return denied;
 return Response.json({products:await getDb().select().from(productCatalog).orderBy(desc(productCatalog.active),productCatalog.category,productCatalog.name)});
}
export async function POST(request:Request){const denied=await requireAdminApi();if(denied)return denied;const b=await request.json() as {name?:string;category?:string;price?:number;effectiveFrom?:string};if(!b.name?.trim()||!b.category?.trim())return Response.json({error:"Name and category are required."},{status:400});const db=getDb(),name=b.name.trim(),category=b.category.trim(),price=Math.max(0,Number(b.price)||0);const existing=(await db.select().from(productCatalog)).find(item=>item.name===name&&item.category===category);if(existing){const [product]=await db.update(productCatalog).set({price,effectiveFrom:b.effectiveFrom??existing.effectiveFrom,active:true}).where(eq(productCatalog.id,existing.id)).returning();return Response.json({product})}const [product]=await db.insert(productCatalog).values({name,category,price,effectiveFrom:b.effectiveFrom??""}).returning();return Response.json({product},{status:201})}
export async function PATCH(request:Request){const denied=await requireAdminApi();if(denied)return denied;const b=await request.json() as {id?:number;name?:string;category?:string;price?:number;effectiveFrom?:string;active?:boolean};if(!b.id)return Response.json({error:"Product is required."},{status:400});const changes:{name?:string;category?:string;price?:number;effectiveFrom?:string;active?:boolean}={};if(b.name!==undefined)changes.name=b.name.trim();if(b.category!==undefined)changes.category=b.category.trim();if(b.price!==undefined)changes.price=Math.max(0,Number(b.price)||0);if(b.effectiveFrom!==undefined)changes.effectiveFrom=b.effectiveFrom;if(b.active!==undefined)changes.active=b.active;const [product]=await getDb().update(productCatalog).set(changes).where(eq(productCatalog.id,b.id)).returning();return product?Response.json({product}):Response.json({error:"Product not found."},{status:404})}
export async function DELETE(request:Request){const denied=await requireAdminApi();if(denied)return denied;const b=await request.json() as {id?:number};if(!b.id)return Response.json({error:"Product is required."},{status:400});const [product]=await getDb().update(productCatalog).set({active:false}).where(eq(productCatalog.id,b.id)).returning();return product?Response.json({success:true}):Response.json({error:"Product not found."},{status:404})}
