"use client";
import { useEffect,useState } from "react";
import { AlertTriangle,ArrowLeft,CheckCircle2,PackageCheck,Plus,Printer,Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
type Item={id:number;areaName:string;productName:string;sku:string;quantity:number;unitCost:number;checked:boolean;notes:string};
type Matrix={areas:string[];components:{name:string;areas:Record<string,number>;total:number}[];hardware:{name:string;total:number}[]};
type Job={id:number;quoteNumber:string;customerName:string;project:string;siteAddress:string;serviceType:string;dispatchStatus:string;pickListStatus:string;pickedBy:string;pickedAt?:string};
type Component={group:string;name:string;cost:number};
const money=(v:number)=>new Intl.NumberFormat("en-NZ",{style:"currency",currency:"NZD",minimumFractionDigits:2}).format(v);
const STANDARD_PARTS=["2.4m Top Support","2.4m Back Support","1800 Side","1200 Side","1200 Shelf","550 Shelf","400 Shelf","1200 Hanging Bar","550 Hanging Bar","400 Hanging Bar","Drawers (400)","Drawers (550)","Starter Ends","Top panel","Side panel","Back panel","Hanging rail","Shelf","Drawer unit","Handle"];
const COMPONENTS:Component[]=[
 ...[1000,900,800,700,600,500,450].map((size,index)=>({group:"Cabinet System",name:`${size} Module`,cost:[381,370,360,349,338,322,316][index]})),
 ...[1000,900,800,700,600,500,450].map((size,index)=>({group:"Cabinet System",name:`${size} Shelf`,cost:[53,48,43,36,33,26,23][index]})),
 {group:"Cabinet System",name:"Back Support (pair)",cost:0},{group:"Cabinet System",name:"Back Panel",cost:0},{group:"Cabinet System",name:"Mid Panel",cost:0},{group:"Cabinet System",name:"LH Seen End",cost:123},{group:"Cabinet System",name:"RH Seen End",cost:123},{group:"Cabinet System",name:"Hanging Bar Standard",cost:22},{group:"Cabinet System",name:"Designer Black Hanging Bar",cost:55},{group:"Cabinet System",name:"Tie Drawer",cost:82},{group:"Cabinet System",name:"100x18 Filler Panel",cost:24},{group:"Cabinet System",name:"New Panel",cost:127},{group:"Cabinet System",name:"3 Drawer 700",cost:485},{group:"Cabinet System",name:"4 Drawer 800",cost:670},{group:"Cabinet System",name:"5 Drawer 700",cost:762},{group:"Cabinet System",name:"5 Drawer 800",cost:818},{group:"Cabinet System",name:"Shelf cut down",cost:19.9985},{group:"Cabinet System",name:"Module cut down",cost:75.00360375},
 ...STANDARD_PARTS.map(name=>({group:"I-Robe / Custom",name,cost:0})),
 ...["Metal cams","Cam dowels","Cam covers (plastic)","Shelf screws","Shelf cams (plastic)","Hanging-bar brackets","Hanging-bar screws","Wood screws (45mm)","Cover caps (stickers)","Instructions"].map(name=>({group:"Hardware",name,cost:0}))
];
export default function PickListPage({params}:{params:Promise<{id:string}>}){
 const [id,setId]=useState(0),[job,setJob]=useState<Job|null>(null),[items,setItems]=useState<Item[]>([]),[matrix,setMatrix]=useState<Matrix>({areas:[],components:[],hardware:[]}),[manualAreas,setManualAreas]=useState<string[]>([]),[componentArea,setComponentArea]=useState(""),[componentGroup,setComponentGroup]=useState("Cabinet System"),[activeList,setActiveList]=useState("I-Robe components"),[quantities,setQuantities]=useState<Record<string,string>>({}),[componentNotes,setComponentNotes]=useState<Record<string,string>>({}),[error,setError]=useState(""),[saving,setSaving]=useState<number|null>(null),[picker,setPicker]=useState("");
 async function load(jobId=id){const r=await fetch(`/api/pick-list/${jobId}`),d=await r.json();if(!r.ok){setError(d.error||"Pick list could not be opened.");return}setJob(d.job);setItems(d.items??[]);setMatrix(d.matrix??{areas:[],components:[],hardware:[]});setManualAreas(d.manualAreas??[]);setComponentArea(current=>current||(d.manualAreas??[]).join(", "))}
 useEffect(()=>{params.then(p=>{const value=Number(p.id);setId(value);load(value)})},[params]);
 const checked=items.filter(x=>x.checked).length,totalCost=items.reduce((sum,x)=>sum+x.quantity*x.unitCost,0),progress=items.length?Math.round(checked/items.length*100):0;
 async function update(item:Item,changes:Partial<Item>){setSaving(item.id);const r=await fetch(`/api/pick-list/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId:item.id,pickedBy:picker,...changes})}),d=await r.json();setSaving(null);if(!r.ok){window.alert(d.error||"This line could not be updated.");return}if(d.items)setItems(d.items);else setItems(current=>current.map(x=>x.id===item.id?{...x,...d.item}:x));setJob(d.job)}
 async function addManual(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form)),r=await fetch(`/api/pick-list/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,action:"manual",quantity:Number(data.quantity),unitCost:Number(data.unitCost)})}),d=await r.json();if(!r.ok){window.alert(d.error||"Manual line could not be added.");return}form.reset();load()}
 async function addComponentQuantities(){const selected=COMPONENTS.filter(part=>part.group===componentGroup&&Number(quantities[part.name])>0).map(part=>({productName:part.name,sku:"",quantity:Number(quantities[part.name]),unitCost:part.cost,areaName:componentArea||"Custom / Cabinet design",notes:componentNotes[part.name]||""}));if(!selected.length){window.alert("Enter at least one component quantity.");return}setSaving(-1);const r=await fetch(`/api/pick-list/${id}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"manual-batch",items:selected})}),d=await r.json();setSaving(null);if(!r.ok){window.alert(d.error||"Components could not be added.");return}setQuantities({});setComponentNotes({});await load()}
 async function remove(item:Item){if(!window.confirm(`Remove ${item.productName} from this pick list?`))return;const r=await fetch(`/api/pick-list/${id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({itemId:item.id})});if(r.ok)load()}
 if(error)return <main className="grid min-h-screen place-items-center bg-slate-100 p-6"><div className="rounded-2xl border bg-white p-8"><h1 className="text-xl font-bold">Unable to open pick list</h1><p className="mt-2 text-slate-600">{error}</p></div></main>;
 if(!job)return <main className="grid min-h-screen place-items-center bg-slate-100">Loading pick list…</main>;
 return <main className="pick-list-print min-h-screen bg-slate-100 p-4 sm:p-8 print:bg-white print:p-0"><article className="mx-auto max-w-6xl rounded-2xl border bg-white shadow-sm print:max-w-none print:border-0 print:shadow-none">
  <header className="border-b-4 border-emerald-700 p-6 sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div className="flex items-center gap-3"><span className="grid size-12 place-items-center rounded-xl bg-emerald-700 text-white"><PackageCheck/></span><div><h1 className="text-2xl font-bold">RobeFlow Warehouse Pick List</h1><p className="text-sm text-slate-500">Enter component quantities, then use one consolidated picking sheet</p></div></div><div className="sm:text-right"><p className="text-2xl font-light tracking-wide text-emerald-700">{job.quoteNumber}</p><p className="font-bold">{job.serviceType}</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-4"><Info label="Customer" value={job.customerName}/><Info label="Project" value={job.project}/><Info label="Dispatch status" value={job.dispatchStatus}/><Info label="Delivery / site" value={job.siteAddress||"Not recorded"}/></div></header>
  <section className="grid gap-4 border-b bg-slate-50 p-5 sm:grid-cols-[1fr_1fr_1fr_auto]"><Info label="Picking progress" value={`${checked} of ${items.length} lines (${progress}%)`}/><Info label="Parts value" value={money(totalCost)}/><div><p className="text-xs font-bold uppercase text-slate-400">Picked by</p><Input className="mt-1 bg-white print:border-0 print:p-0" value={picker||job.pickedBy||""} onChange={e=>setPicker(e.target.value)} placeholder="Warehouse team member"/></div><div className="flex items-end gap-2 print:hidden"><Button variant="outline" onClick={()=>history.back()}><ArrowLeft/>Back</Button><Button onClick={()=>window.print()}><Printer/>Print</Button></div></section>
  <div className="p-5 sm:p-8">{manualAreas.length>0&&<div className="mb-5 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-amber-950 print:hidden"><AlertTriangle className="mt-0.5 size-5 shrink-0"/><div><p className="font-bold">Component quantities required</p><p className="mt-1 text-sm">Use the sheet below for Cabinet System or custom designs in: {manualAreas.join(", ")}.</p></div></div>}
   <ComponentEntry {...{componentGroup,setComponentGroup,componentArea,setComponentArea,quantities,setQuantities,componentNotes,setComponentNotes,saving}} onAdd={addComponentQuantities}/>
   <div className="mb-4 flex flex-wrap gap-2 print:hidden">{CHECKLIST_TABS.map(tab=><Button type="button" key={tab} variant={activeList===tab?"default":"outline"} onClick={()=>setActiveList(tab)}>{tab}<span className="ml-1 rounded-full bg-black/10 px-2 py-0.5 text-xs">{items.filter(item=>sectionFor(item)===tab).length}</span></Button>)}</div>
   {CHECKLIST_TABS.map(tab=><ChecklistSection key={tab} title={tab} items={items.filter(item=>sectionFor(item)===tab)} active={activeList===tab} saving={saving} onUpdate={update} onRemove={remove}/>) }
   <form onSubmit={addManual} className="rounded-xl border border-dashed bg-slate-50 p-4 print:hidden"><div className="mb-3"><h3 className="font-bold">Add a component not listed above</h3><p className="text-sm text-slate-500">Matching lines are automatically combined in the final checklist.</p></div><div className="grid gap-3 md:grid-cols-2"><Input name="areaName" placeholder="Area(s), e.g. Bedroom 1, Bedroom 2"/><Input name="productName" required placeholder="Component name"/><Input name="sku" placeholder="Product code / SKU (optional)"/><Input name="notes" placeholder="Colour, size or cutting note"/></div><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-end"><div className="grid flex-1 gap-1"><label className="text-sm font-semibold">Quantity</label><Input name="quantity" required type="number" min="0.5" step="0.5" placeholder="Qty"/></div><div className="grid flex-1 gap-1"><label className="text-sm font-semibold">Unit cost</label><Input name="unitCost" type="number" min="0" step="0.01" placeholder="$0.00"/></div><Button><Plus/>Add item</Button></div></form>
   <PrintMatrix matrix={matrix}/>
   {job.pickListStatus==="Picked"&&<div className="mt-6 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-900"><CheckCircle2/><div><p className="font-bold">Picking complete</p><p className="text-sm">Completed by {job.pickedBy||"Warehouse team"}{job.pickedAt?` on ${new Date(job.pickedAt).toLocaleString("en-NZ")}`:""}</p></div></div>}
  </div></article></main>
}
function ComponentEntry({componentGroup,setComponentGroup,componentArea,setComponentArea,quantities,setQuantities,componentNotes,setComponentNotes,saving,onAdd}:{componentGroup:string;setComponentGroup:(v:string)=>void;componentArea:string;setComponentArea:(v:string)=>void;quantities:Record<string,string>;setQuantities:React.Dispatch<React.SetStateAction<Record<string,string>>>;componentNotes:Record<string,string>;setComponentNotes:React.Dispatch<React.SetStateAction<Record<string,string>>>;saving:number|null;onAdd:()=>void}){const rows=COMPONENTS.filter(part=>part.group===componentGroup);return <section className="mb-6 overflow-hidden rounded-xl border bg-white print:hidden"><div className="flex flex-col gap-3 border-b bg-emerald-50 p-4 sm:flex-row sm:items-end"><div className="grid flex-1 gap-1"><label className="text-sm font-bold">Component sheet</label><select value={componentGroup} onChange={e=>setComponentGroup(e.target.value)} className="h-10 rounded-md border bg-white px-3"><option>Cabinet System</option><option>I-Robe / Custom</option><option>Hardware</option></select></div><div className="grid flex-[2] gap-1"><label className="text-sm font-bold">Area(s)</label><Input value={componentArea} onChange={e=>setComponentArea(e.target.value)} placeholder="Bedroom 1, Bedroom 2, Storage"/></div></div><div className="max-h-[32rem] overflow-auto"><table className="w-full min-w-[700px] text-sm"><thead className="sticky top-0 bg-slate-900 text-white"><tr><th className="p-3 text-left">Component</th><th className="w-28 p-3 text-right">Unit cost</th><th className="w-28 p-3 text-right">Quantity</th><th className="w-72 p-3 text-left">Colour / cut / note</th></tr></thead><tbody>{rows.map(part=><tr key={part.name} className="border-t even:bg-slate-50"><td className="p-3 font-semibold">{part.name}</td><td className="p-3 text-right text-slate-500">{part.cost?money(part.cost):"—"}</td><td className="p-2"><Input type="number" min="0" step="0.5" value={quantities[part.name]||""} onChange={e=>setQuantities(current=>({...current,[part.name]:e.target.value}))} className="ml-auto w-24 text-right font-bold" placeholder="0"/></td><td className="p-2"><Input value={componentNotes[part.name]||""} onChange={e=>setComponentNotes(current=>({...current,[part.name]:e.target.value}))} placeholder="Optional"/></td></tr>)}</tbody></table></div><div className="flex justify-end border-t p-4"><Button type="button" disabled={saving===-1} onClick={onAdd}><Plus/>{saving===-1?"Adding…":"Add entered quantities"}</Button></div></section>}
const CHECKLIST_TABS=["I-Robe components","I-Robe hardware","Cabinet components","Cabinet hardware","Accessories / other"];
const CABINET_NAMES=new Set(COMPONENTS.filter(x=>x.group==="Cabinet System").map(x=>x.name));
function sectionFor(item:Item){if(item.notes==="Automatically calculated from Cabinet System components")return "Cabinet hardware";if(item.notes==="Automatically calculated from I-Robe components")return "I-Robe hardware";if(CABINET_NAMES.has(item.productName))return "Cabinet components";if(STANDARD_PARTS.includes(item.productName))return "I-Robe components";return "Accessories / other"}
function ChecklistSection({title,items,active,saving,onUpdate,onRemove}:{title:string;items:Item[];active:boolean;saving:number|null;onUpdate:(item:Item,changes:Partial<Item>)=>void;onRemove:(item:Item)=>void}){if(!items.length)return null;return <section className={`${active?"block":"hidden"} mb-6 break-inside-avoid print:block print:break-before-page print:first:break-before-auto`}><h2 className="rounded-t-xl bg-slate-900 px-4 py-3 font-bold text-white">{title}</h2><div className="overflow-x-auto rounded-b-xl border border-t-0 print:overflow-visible"><table className="w-full min-w-[760px] text-sm print:min-w-0"><thead><tr className="bg-slate-100 text-left text-slate-600"><th className="w-14 p-3 text-center">Pick</th><th className="p-3">Product</th><th className="p-3">Used in areas</th><th className="w-32 p-3">Code</th><th className="w-24 p-3 text-right">Total qty</th><th className="w-28 p-3 text-right">Unit cost</th><th className="w-28 p-3 text-right">Line value</th><th className="w-14 p-3 print:hidden"></th></tr></thead><tbody>{items.map(item=><tr key={item.id} className={`border-t ${item.checked?"bg-emerald-50":""}`}><td className="p-3 text-center"><input type="checkbox" checked={item.checked} disabled={saving===item.id} onChange={e=>onUpdate(item,{checked:e.target.checked})} className="size-5 accent-emerald-700"/></td><td className="p-3"><p className={`font-semibold ${item.checked?"text-emerald-800 line-through":""}`}>{item.productName}</p>{item.notes&&!item.notes.startsWith("Automatically calculated")&&<p className="mt-1 text-xs text-slate-500">{item.notes}</p>}</td><td className="p-3 text-slate-600">{item.areaName}</td><td className="p-3 text-slate-500">{item.sku||"—"}</td><td className="p-3 text-right"><Input type="number" min="0.5" step="0.5" defaultValue={item.quantity} disabled={item.notes.startsWith("Automatically calculated")} onBlur={e=>Number(e.target.value)!==item.quantity&&onUpdate(item,{quantity:Number(e.target.value)})} className="ml-auto w-20 text-right font-bold print:border-0 disabled:bg-transparent"/></td><td className="p-3 text-right">{money(item.unitCost)}</td><td className="p-3 text-right font-semibold">{money(item.quantity*item.unitCost)}</td><td className="p-3 print:hidden">{!item.notes.startsWith("Automatically calculated")&&<Button size="icon" variant="ghost" className="text-red-600" onClick={()=>onRemove(item)}><Trash2 className="size-4"/></Button>}</td></tr>)}</tbody></table></div></section>}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 font-semibold text-slate-800">{value}</p></div>}

function PrintMatrix({matrix}:{matrix:Matrix}){return <section className="hidden print:block"><h2 className="mb-3 text-xl font-bold">Consolidated job pick sheet</h2><table className="w-full border-collapse text-[10px]"><thead><tr className="bg-slate-900 text-white"><th className="border p-2 text-left">Item</th>{matrix.areas.map(area=><th key={area} className="border p-2 text-center">{area}</th>)}<th className="border bg-amber-300 p-2 text-center text-slate-950">TOTAL</th><th className="border p-2 text-center">Checked</th></tr></thead><tbody>{matrix.components.map(row=><tr key={row.name}><td className="border p-2 font-semibold">{row.name}</td>{matrix.areas.map(area=><td key={area} className="border p-2 text-center">{row.areas[area]||""}</td>)}<td className="border bg-yellow-200 p-2 text-center font-bold">{row.total}</td><td className="border p-2 text-center">□</td></tr>)}</tbody></table><h2 className="mt-6 rounded-t bg-slate-900 p-2 text-sm font-bold text-white">Hardware — whole job total</h2><table className="w-full border-collapse text-[10px]"><thead><tr className="bg-slate-100"><th className="border p-2 text-left">Hardware</th><th className="w-24 border p-2">Total</th><th className="w-24 border p-2">Checked</th></tr></thead><tbody>{matrix.hardware.map(row=><tr key={row.name}><td className="border p-2 font-semibold">{row.name}</td><td className="border p-2 text-center font-bold">{row.total}</td><td className="border p-2 text-center">□</td></tr>)}</tbody></table></section>}
