"use client";
import { useEffect,useMemo,useState } from "react";
import { AlertTriangle,Archive,BarChart3,Bell,CalendarClock,ChevronLeft,ChevronRight,Download,Mail,MapPin,PackageCheck,PackagePlus,Plus,RotateCcw,Save,Settings2,Truck,Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { ACCESSORY_OPTIONS,IROBE_OPTIONS } from "../lib/quote-options";

type Quote={id:number;quoteNumber:string;customerName:string;email?:string;phone?:string;siteAddress?:string;project:string;status:string;invoiceStatus:string;validUntil:string;followUpDate:string;jobStage:string;salespersonName:string;serviceType:string;accountsApproved:boolean;dispatchStatus:string;trackingNumber:string;trackingSentAt?:string;pickListStatus:string;pickListFileName?:string;pickListUploadedAt?:string;pickListUploadedBy?:string;pickListOpened?:boolean;amount:number};
const stages=["Awaiting acceptance","Site measure required","Measure booked","Measurement completed","Design approved","Deposit received","Materials ordered","Ready for installation","Installation booked","Installed","Completed"];
export function OperationsPanel(){
 type Event={id:number;quoteId:number;eventType:string;scheduledDate:string;startTime:string;endTime:string;assignedTo:string;notes:string;status:string;quoteNumber:string;customerName:string;project:string;siteAddress:string};
 const blank={quoteId:0,eventType:"Site measure",scheduledDate:new Date().toISOString().slice(0,10),startTime:"09:00",endTime:"10:00",assignedTo:"",notes:"",status:"Scheduled"};
 const [quotes,setQuotes]=useState<Quote[]>([]),[events,setEvents]=useState<Event[]>([]),[search,setSearch]=useState(""),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[open,setOpen]=useState(false),[editing,setEditing]=useState<Event|null>(null),[form,setForm]=useState(blank),[saving,setSaving]=useState(false),[error,setError]=useState("");
 async function load(){const [qr,er]=await Promise.all([fetch("/api/quotes"),fetch("/api/schedule")]);const [qd,ed]=await Promise.all([qr.json(),er.json()]);setQuotes(qd.quotes??[]);setEvents(ed.events??[])}
 useEffect(()=>{load()},[]);
 const rows=useMemo(()=>quotes.filter(q=>q.status==="Accepted"&&q.serviceType==="Installation"&&`${q.quoteNumber} ${q.customerName} ${q.project} ${q.jobStage}`.toLowerCase().includes(search.toLowerCase())),[quotes,search]);
 const accepted=quotes.filter(q=>q.status==="Accepted"&&q.serviceType==="Installation"),monthKey=`${month.getFullYear()}-${String(month.getMonth()+1).padStart(2,"0")}`;
 const days=useMemo(()=>{const first=(month.getDay()+6)%7,count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();return [...Array(first).fill(null),...Array.from({length:count},(_,i)=>i+1)]},[month]);
 function start(date?:string){setEditing(null);setError("");setForm({...blank,quoteId:accepted[0]?.id??0,scheduledDate:date??blank.scheduledDate,assignedTo:accepted[0]?.salespersonName??""});setOpen(true)}
 function edit(event:Event){setEditing(event);setError("");setForm({quoteId:event.quoteId,eventType:event.eventType,scheduledDate:event.scheduledDate,startTime:event.startTime,endTime:event.endTime,assignedTo:event.assignedTo,notes:event.notes,status:event.status});setOpen(true)}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError("");const r=await fetch("/api/schedule",{method:editing?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,id:editing?.id})});const d=await r.json();setSaving(false);if(!r.ok){setError(d.error||"The booking could not be saved.");return}setOpen(false);await load()}
 async function removeEvent(){if(!editing||!window.confirm("Delete this calendar booking?"))return;const r=await fetch("/api/schedule",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:editing.id})});if(r.ok){setOpen(false);load()}}
 async function update(q:Quote,changes:Partial<Quote>){const r=await fetch(`/api/quotes/${q.id}/workflow`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...changes,actor:q.salespersonName})});if(r.ok){const d=await r.json();setQuotes(current=>current.map(x=>x.id===q.id?{...x,...d.quote}:x))}}
 async function remove(q:Quote){if(!window.confirm(`Archive ${q.quoteNumber} for ${q.customerName}? You can restore it later from Archive.`))return;const r=await fetch(`/api/quotes/${q.id}`,{method:"DELETE"});if(r.ok)setQuotes(current=>current.filter(item=>item.id!==q.id));else window.alert("The job could not be archived.")}
 return <div className="space-y-6"><section className="flex flex-col gap-4 rounded-2xl border bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">Job scheduling calendar</h2><p className="mt-1 text-sm text-slate-500">Book site measures and installations for accepted jobs.</p></div><Button onClick={()=>start()} disabled={!accepted.length}><Plus className="size-4"/>New booking</Button></section>
 <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><header className="flex items-center justify-between border-b p-4"><Button variant="outline" size="icon" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} aria-label="Previous month"><ChevronLeft/></Button><h3 className="text-lg font-bold">{month.toLocaleDateString("en-NZ",{month:"long",year:"numeric"})}</h3><Button variant="outline" size="icon" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} aria-label="Next month"><ChevronRight/></Button></header><div className="grid grid-cols-7 border-b bg-slate-50 text-center text-xs font-bold uppercase text-slate-500">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><span key={d} className="p-2">{d}</span>)}</div><div className="grid grid-cols-7">{days.map((day,index)=>{const date=day?`${monthKey}-${String(day).padStart(2,"0")}`:"",bookings=events.filter(e=>e.scheduledDate===date&&e.status!=="Cancelled");return <button key={index} type="button" disabled={!day} onClick={()=>day&&start(date)} className="min-h-24 border-b border-r p-1.5 text-left align-top hover:bg-emerald-50 disabled:bg-slate-50 sm:min-h-32"><span className="text-sm font-semibold">{day}</span><span className="mt-1 block space-y-1">{bookings.slice(0,3).map(e=><span key={e.id} onClick={x=>{x.stopPropagation();edit(e)}} className={`block truncate rounded px-1.5 py-1 text-xs font-semibold ${e.eventType==="Installation"?"bg-indigo-100 text-indigo-800":"bg-emerald-100 text-emerald-800"}`}>{e.startTime} {e.customerName}</span>)}{bookings.length>3&&<span className="block text-xs text-slate-500">+{bookings.length-3} more</span>}</span></button>})}</div></section>
 <section className="rounded-2xl border bg-white p-5 shadow-sm"><h3 className="font-bold">Accepted installation jobs</h3><Input className="mt-4 max-w-md" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search installation jobs…"/><div className="mt-4 grid gap-3">{rows.map(q=><article key={q.id} className="rounded-xl border p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-emerald-700">{q.quoteNumber}</p><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${q.invoiceStatus==="Paid in Full"?"bg-emerald-100 text-emerald-800":q.invoiceStatus==="To invoice"?"bg-amber-100 text-amber-800":"bg-violet-100 text-violet-800"}`}>{q.invoiceStatus==="To invoice"?"Invoice pending":q.invoiceStatus}</span></div><h4 className="font-bold">{q.customerName} · {q.project}</h4><p className="text-sm text-slate-500">Assigned to {q.salespersonName}</p></div><div className="flex gap-2"><a href={`/api/quotes/${q.id}/pdf`} className="inline-flex h-9 items-center gap-2 rounded-md border px-3 text-sm font-medium"><Download className="size-4"/>Quote</a><Button variant="outline" size="sm" onClick={()=>{setForm({...blank,quoteId:q.id,assignedTo:q.salespersonName});setEditing(null);setOpen(true)}}><CalendarClock/>Book</Button><Button size="icon" variant="outline" className="text-red-600" onClick={()=>remove(q)} aria-label={`Archive ${q.quoteNumber}`}><Trash2 className="size-4"/></Button></div></div><div className="mt-4 grid gap-3 border-t pt-4 sm:grid-cols-2"><div><Label>Job stage</Label><select className="mt-2 h-10 w-full rounded-md border bg-white px-3" value={q.jobStage||"Site measure required"} onChange={e=>update(q,{jobStage:e.target.value})}>{stages.map(s=><option key={s}>{s}</option>)}</select></div><div><Label>Next follow-up</Label><Input className="mt-2" type="date" value={q.followUpDate||""} onChange={e=>update(q,{followUpDate:e.target.value})}/></div></div></article>)}</div>{!rows.length&&<p className="py-8 text-center text-slate-500">No accepted installation jobs yet.</p>}</section>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-xl"><form onSubmit={save}><DialogHeader><DialogTitle>{editing?"Edit booking":"Schedule a job"}</DialogTitle><DialogDescription>Bookings are shared with the operations team and checked for staff conflicts.</DialogDescription></DialogHeader><div className="grid gap-4 py-5 sm:grid-cols-2"><div className="sm:col-span-2"><Label>Accepted job</Label><select required className="mt-2 h-10 w-full rounded-md border bg-white px-3" value={form.quoteId} onChange={e=>{const id=Number(e.target.value),q=accepted.find(x=>x.id===id);setForm({...form,quoteId:id,assignedTo:q?.salespersonName||form.assignedTo})}}><option value={0}>Select job</option>{accepted.map(q=><option key={q.id} value={q.id}>{q.quoteNumber} · {q.customerName} · {q.project}</option>)}</select></div><div><Label>Booking type</Label><select className="mt-2 h-10 w-full rounded-md border bg-white px-3" value={form.eventType} onChange={e=>setForm({...form,eventType:e.target.value})}><option>Site measure</option><option>Installation</option></select></div><div><Label>Status</Label><select className="mt-2 h-10 w-full rounded-md border bg-white px-3" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>Scheduled</option><option>Completed</option><option>Cancelled</option></select></div><div><Label>Date</Label><Input className="mt-2" required type="date" value={form.scheduledDate} onChange={e=>setForm({...form,scheduledDate:e.target.value})}/></div><div><Label>Assigned staff member</Label><Input className="mt-2" required value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})} placeholder="Staff name"/></div><div><Label>Start time</Label><Input className="mt-2" required type="time" value={form.startTime} onChange={e=>setForm({...form,startTime:e.target.value})}/></div><div><Label>End time</Label><Input className="mt-2" required type="time" value={form.endTime} onChange={e=>setForm({...form,endTime:e.target.value})}/></div><div className="sm:col-span-2"><Label>Notes</Label><textarea className="mt-2 min-h-20 w-full rounded-md border p-3 text-sm" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="Access details, contact instructions or installation notes"/></div></div>{editing?.siteAddress&&<p className="mb-4 flex gap-2 rounded-lg bg-slate-50 p-3 text-sm"><MapPin className="size-4 shrink-0"/>{editing.siteAddress}</p>}{error&&<p className="mb-4 text-sm font-semibold text-red-600">{error}</p>}<DialogFooter className="justify-between sm:justify-between">{editing?<Button type="button" variant="destructive" onClick={removeEvent}>Delete booking</Button>:<span/>}<div className="flex gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={saving}>{saving?"Saving…":"Save booking"}</Button></div></DialogFooter></form></DialogContent></Dialog></div>
}

export function DispatchPanel(){
 const [jobs,setJobs]=useState<Quote[]>([]),[search,setSearch]=useState(""),[tab,setTab]=useState("Installation"),[saving,setSaving]=useState<number|null>(null),[tracking,setTracking]=useState<Record<number,string>>({});
 const set=(read:(event:{target:{value:string}})=>string)=>{const target=(window.event?.target as HTMLInputElement|null);setSearch(read({target:{value:target?.value||""}}))};
 async function load(){const r=await fetch("/api/dispatch"),d=await r.json();setJobs(d.jobs??[]);setTracking(Object.fromEntries((d.jobs??[]).map((q:Quote)=>[q.id,q.trackingNumber||""])))}
 useEffect(()=>{load()},[]);
 const shown=jobs.filter(q=>(tab==="Supply"?q.serviceType==="Pick Up":tab==="Freight & Delivery"?["Freight","Delivery"].includes(q.serviceType):q.serviceType==="Installation")&&`${q.quoteNumber} ${q.customerName} ${q.project} ${q.serviceType} ${q.dispatchStatus} ${q.pickListFileName||""}`.toLowerCase().includes(search.toLowerCase()));
 async function update(q:Quote,changes:{dispatchStatus?:string;trackingNumber?:string}){setSaving(q.id);try{const r=await fetch("/api/dispatch",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:q.id,...changes})}),d=await r.json();if(!r.ok){window.alert(d.error||"Dispatch details could not be saved.");return}if(d.notified)window.alert(`Tracking details were emailed to ${q.email}.`);await load()}finally{setSaving(null)}}
 async function openPickList(q:Quote){window.open(`/pick-list/${q.id}`,"_blank","noopener,noreferrer");if(!q.pickListUploadedAt)return;const r=await fetch(`/api/pick-list/${q.id}/documents`,{method:"PATCH"}),d=await r.json().catch(()=>({}));if(!r.ok){window.alert(d.error||"The pick list could not be opened.");return}setJobs(current=>current.map(job=>job.id===q.id?{...job,pickListOpened:true}:job))}
 return <div className="space-y-6">
  <section className="rounded-2xl border bg-white p-5 shadow-sm">
   <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="flex items-center gap-2 text-xl font-bold"><Truck className="text-emerald-700"/>Dispatch jobs</h2><p className="mt-1 text-sm text-slate-500">Open the current pick list before progressing an approved job through Dispatch.</p></div><Input className="sm:max-w-sm" value={search} onChange={e=>set(s=>s.target.value)} placeholder="Search dispatch jobs…"/></div>
   <div className="mt-4 flex flex-wrap gap-2 border-t pt-4">{["Installation","Supply","Freight & Delivery"].map(name=><Button key={name} variant={tab===name?"default":"outline"} size="sm" onClick={()=>setTab(name)}>{name}<span className="rounded-full bg-white/20 px-1.5 text-xs">{jobs.filter(q=>name==="Supply"?q.serviceType==="Pick Up":name==="Freight & Delivery"?["Freight","Delivery"].includes(q.serviceType):q.serviceType==="Installation").length}</span></Button>)}</div>
  </section>
  <section className="grid gap-4">{shown.map(q=>{const hasPickList=!!q.pickListUploadedAt,options=q.serviceType==="Installation"?["Awaiting dispatch","Ready","Completed"]:q.serviceType==="Pick Up"?["Awaiting dispatch","Ready for Pickup","Collected"]:["Awaiting dispatch","Dispatched","Completed"],trackingJob=["Freight","Delivery"].includes(q.serviceType),trackingSent=!!q.trackingSentAt,trackingEditable=q.dispatchStatus==="Dispatched"&&!trackingSent;return <article key={q.id} className="rounded-2xl border bg-white p-5 shadow-sm">
   <div className="flex flex-col justify-between gap-4 lg:flex-row"><div><div className="flex flex-wrap items-center gap-2"><span className="font-bold text-emerald-700">{q.quoteNumber}</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{q.serviceType}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${q.invoiceStatus==="Paid in Full"?"bg-emerald-100 text-emerald-800":"bg-violet-100 text-violet-800"}`}>{q.invoiceStatus}</span><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${hasPickList?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-800"}`}>{hasPickList?q.pickListOpened?"Pick list opened":"Open pick list to continue":"Pick list required"}</span></div><h3 className="mt-2 text-lg font-bold">{q.customerName} · {q.project}</h3><p className="mt-1 text-sm text-slate-500">{q.siteAddress||"No delivery/site address recorded"}</p>{q.email&&<p className="mt-1 flex items-center gap-2 text-sm text-slate-500"><Mail className="size-4"/>{q.email}</p>}{hasPickList&&<div className="mt-3 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-900"><p className="truncate font-semibold">{q.pickListFileName}</p><p className="mt-1">Uploaded by {q.pickListUploadedBy||"RobeFlow staff"} · {new Date(q.pickListUploadedAt!).toLocaleString("en-NZ")}</p></div>}</div><div className="flex flex-wrap items-start gap-2"><button type="button" onClick={()=>openPickList(q)} className="inline-flex h-9 items-center gap-2 rounded-md bg-emerald-700 px-3 text-sm font-medium text-white"><PackageCheck className="size-4"/>{hasPickList?"Open current pick list":"Upload pick list"}</button><a href={`/api/quotes/${q.id}/pdf`} className="inline-flex h-9 items-center gap-2 rounded-md border px-3 text-sm font-medium"><Download className="size-4"/>Quote</a>{q.invoiceStatus!=="To be Invoiced"&&<a href={`/api/invoices/${q.id}/pdf`} className="inline-flex h-9 items-center gap-2 rounded-md border px-3 text-sm font-medium"><Download className="size-4"/>Invoice</a>}</div></div>
  <div className="mt-5 grid gap-3 border-t pt-4 md:grid-cols-[13rem_1fr_auto]"><div><Label>Dispatch status</Label><select disabled={!q.pickListOpened||saving===q.id} className="mt-2 h-10 w-full rounded-md border bg-white px-3 disabled:cursor-not-allowed disabled:bg-slate-100" value={q.dispatchStatus||"Awaiting dispatch"} onChange={e=>update(q,{dispatchStatus:e.target.value})}>{options.map(option=><option key={option}>{option}</option>)}</select>{!q.pickListOpened&&<p className="mt-1 text-xs font-medium text-amber-700">Open the current pick list to unlock statuses.</p>}</div>{trackingJob?<div><Label>Tracking number</Label><Input disabled={!trackingEditable||saving===q.id} className="mt-2 disabled:cursor-not-allowed disabled:bg-slate-100" value={tracking[q.id]??""} onChange={e=>setTracking(v=>({...v,[q.id]:e.target.value}))} placeholder={trackingSent?"Tracking details emailed":q.dispatchStatus==="Dispatched"?"Enter carrier tracking number":"Set status to Dispatched first"}/>{trackingSent&&<p className="mt-1 text-xs font-medium text-emerald-700">Tracking details emailed. The number is now locked.</p>}</div>:<div><Label>Dispatch note</Label><p className="mt-2 text-sm text-slate-500">{hasPickList?"The Excel file is available for Dispatch review.":"Upload the Excel pick list before dispatching this job."}</p></div>}{trackingJob&&<Button className="self-end" disabled={!q.pickListOpened||saving===q.id||!trackingEditable||!(tracking[q.id]??"").trim()} onClick={()=>update(q,{trackingNumber:tracking[q.id]})}><PackageCheck className="size-4"/>{saving===q.id?"Sending…":trackingSent?"Tracking emailed":"Email tracking details"}</Button>}</div>
  </article>})}{!shown.length&&<div className="rounded-2xl border bg-white p-12 text-center text-slate-500"><Truck className="mx-auto mb-3 size-8"/>No approved jobs in this tab.</div>}</section>
 </div>
}

type Product={id:number;name:string;category:string;price:number;effectiveFrom:string;active:boolean};
export function ProductsPanel(){
 const [products,setProducts]=useState<Product[]>([]),[saving,setSaving]=useState(false),[search,setSearch]=useState(""),[category,setCategory]=useState("I-Robe"),[productName,setProductName]=useState(""),[message,setMessage]=useState("");
 async function load(){const r=await fetch("/api/products");const d=await r.json().catch(()=>({}));if(!r.ok){setMessage(d.error||"Prices could not be loaded.");return}setProducts(d.products??[]);setMessage("")}
 useEffect(()=>{void load()},[]);
 const shown=products.filter(p=>p.active&&`${p.name} ${p.category}`.toLowerCase().includes(search.toLowerCase()));
 const choices=category==="I-Robe"?IROBE_OPTIONS.filter(([name])=>name!=="Custom design").map(([name])=>name):category==="Accessories"?ACCESSORY_OPTIONS:category==="Systems"?["I-Robe Premium","Cabinet System","Free Standing Wardrobe","Linen","Sliding Doors"]:[];
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage("");const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));const r=await fetch("/api/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,name:productName,category})});const d=await r.json().catch(()=>({}));setSaving(false);if(r.ok){const saved=d.product as Product;setProducts(current=>[saved,...current.filter(item=>item.id!==saved.id)]);form.reset();setProductName("");setMessage(`${saved.name} price saved successfully.`)}else{setMessage(d.error||"The price could not be saved.")}}
 async function edit(product:Product){const value=window.prompt(`Update the price for ${product.name}`,String(product.price));if(value===null)return;const price=Number(value);if(!Number.isFinite(price)||price<0){window.alert("Enter a valid price.");return}const r=await fetch("/api/products",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...product,price})});if(r.ok)load()}
 async function remove(product:Product){if(!window.confirm(`Delete ${product.name} from the pricing list and New Quote product choices?`))return;const r=await fetch("/api/products",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:product.id})});if(r.ok)load()}
 return <div className="space-y-6"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-bold"><Settings2 className="text-emerald-700"/>Products & pricing</h2><p className="mt-1 text-sm text-slate-500">Choose a category and product, then set its price. That price automatically appears when the same product is selected in New Quote.</p><form onSubmit={add} className="mt-5 grid gap-3 md:grid-cols-[12rem_1fr_9rem_10rem_auto]"><select value={category} onChange={e=>{setCategory(e.target.value);setProductName("")}} className="h-10 rounded-md border bg-white px-3" aria-label="Product category"><option>I-Robe</option><option>Accessories</option><option>Systems</option><option>Services</option></select>{choices.length?<select required value={productName} onChange={e=>setProductName(e.target.value)} className="h-10 rounded-md border bg-white px-3" aria-label="Product"><option value="">Select product</option>{choices.map(name=><option key={name}>{name}</option>)}</select>:<Input required value={productName} onChange={e=>setProductName(e.target.value)} placeholder="Enter service name"/>}<Input name="price" required type="number" min="0" step="0.01" placeholder="Price"/><Input name="effectiveFrom" type="date"/><Button disabled={saving||!productName}><Plus/>{saving?"Saving…":"Save price"}</Button></form>{message&&<p className={`mt-3 text-sm font-semibold ${message.includes("successfully")?"text-emerald-700":"text-red-600"}`}>{message}</p>}<Input className="mt-4 max-w-md" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products and prices…"/></section><section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="grid grid-cols-[1fr_8rem_7rem] bg-slate-900 px-5 py-3 text-sm font-semibold text-white sm:grid-cols-[1fr_10rem_8rem_9rem]"><span>Product</span><span className="hidden sm:block">Effective</span><span className="text-right">Price</span><span className="text-right">Actions</span></div>{shown.map(p=><div key={p.id} className="grid grid-cols-[1fr_8rem_7rem] items-center border-t px-5 py-4 sm:grid-cols-[1fr_10rem_8rem_9rem]"><div><strong>{p.name}</strong><p className="text-xs text-slate-500">{p.category}</p></div><span className="hidden text-sm sm:block">{p.effectiveFrom||"Not set"}</span><strong className="text-right">${p.price.toLocaleString("en-NZ")}</strong><div className="flex justify-end gap-1"><Button size="sm" variant="outline" onClick={()=>edit(p)}>Edit price</Button><Button size="icon" variant="ghost" className="text-red-600" onClick={()=>remove(p)} aria-label={`Delete ${p.name}`}><Trash2 className="size-4"/></Button></div></div>)}{!shown.length&&<div className="p-12 text-center text-slate-500"><PackagePlus className="mx-auto mb-3"/>No saved prices yet. Choose a product above and save its price.</div>}</section></div>
}

export function ActionCentre({quotes}:{quotes:Quote[]}){const today=new Date().toISOString().slice(0,10),soon=new Date(Date.now()+7*86400000).toISOString().slice(0,10);const cards=[{label:"Follow-ups overdue",value:quotes.filter(q=>q.followUpDate&&q.followUpDate<today&&!["Accepted","Declined","Completed"].includes(q.status)).length,icon:<CalendarClock/>},{label:"Quotes expiring soon",value:quotes.filter(q=>q.status==="Sent"&&q.validUntil>=today&&q.validUntil<=soon).length,icon:<AlertTriangle/>},{label:"Invoices pending",value:quotes.filter(q=>q.status==="Accepted"&&(!q.invoiceStatus||q.invoiceStatus==="To invoice")).length,icon:<AlertTriangle/>},{label:"Jobs awaiting measure",value:quotes.filter(q=>q.status==="Accepted"&&q.jobStage==="Site measure required").length,icon:<CalendarClock/>}];return <section><h2 className="mb-3 text-lg font-bold">Action required</h2><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(c=><article key={c.label} className="rounded-xl border bg-white p-4 shadow-sm"><div className="flex items-center justify-between text-slate-500"><span className="text-sm font-medium">{c.label}</span><span className="[&>svg]:size-4">{c.icon}</span></div><p className="mt-2 text-3xl font-bold">{c.value}</p></article>)}</div></section>}

type Reminder={id:string;type:string;urgency:string;quoteNumber:string;customerName:string;message:string;date:string};
export function ReminderCentre(){const [reminders,setReminders]=useState<Reminder[]>([]);useEffect(()=>{fetch("/api/reminders").then(r=>r.ok?r.json():null).then(d=>setReminders(d?.reminders??[])).catch(()=>{})},[]);if(!reminders.length)return null;return <section className="rounded-2xl border border-amber-200 bg-amber-50/70 p-5"><div className="flex items-center justify-between"><div><h2 className="flex items-center gap-2 text-lg font-bold text-amber-950"><Bell className="size-5"/>Automatic reminders</h2><p className="mt-1 text-sm text-amber-800">RobeFlow checks expiring quotes and unpaid invoices whenever the dashboard opens.</p></div><span className="rounded-full bg-amber-200 px-3 py-1 text-sm font-bold text-amber-950">{reminders.length}</span></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{reminders.slice(0,6).map(item=><article key={item.id} className="rounded-xl border border-amber-200 bg-white p-3"><div className="flex justify-between gap-3"><div><p className="font-semibold">{item.quoteNumber} · {item.customerName}</p><p className="mt-1 text-sm text-slate-600">{item.message}</p></div><span className="h-fit rounded-full bg-amber-100 px-2 py-1 text-xs font-bold text-amber-800">{item.urgency}</span></div><p className="mt-2 text-xs text-slate-500">{item.type} · {new Date(`${item.date}T00:00:00`).toLocaleDateString("en-NZ")}</p></article>)}</div>{reminders.length>6&&<p className="mt-3 text-sm font-semibold text-amber-900">+{reminders.length-6} more reminders</p>}</section>}

type ReportQuote={salespersonName?:string;status:string;amount:number;createdAt?:string};
export function SalesReports({quotes}:{quotes:ReportQuote[]}){const won=(q:ReportQuote)=>["Accepted","Completed"].includes(q.status),salespeople=Array.from(new Set(quotes.map(q=>q.salespersonName||"Unassigned"))).sort(),bySalesperson=salespeople.map(name=>{const rows=quotes.filter(q=>(q.salespersonName||"Unassigned")===name),decided=rows.filter(q=>won(q)||q.status==="Declined");return {name,quotes:rows.length,wins:rows.filter(won).length,sales:rows.filter(won).reduce((sum,q)=>sum+q.amount,0),conversion:decided.length?Math.round(rows.filter(won).length/decided.length*100):0}}),now=new Date(),months=Array.from({length:6},(_,offset)=>{const date=new Date(now.getFullYear(),now.getMonth()-5+offset,1),key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`;return {key,label:date.toLocaleDateString("en-NZ",{month:"short"}),value:quotes.filter(q=>won(q)&&(q.createdAt||"").startsWith(key)).reduce((sum,q)=>sum+q.amount,0)}}),max=Math.max(1,...months.map(m=>m.value));return <section className="grid gap-4 xl:grid-cols-[1.25fr_1fr]"><article className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><BarChart3 className="size-5 text-emerald-700"/>Salesperson performance</h2><div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="py-2">Salesperson</th><th className="py-2 text-right">Quotes</th><th className="py-2 text-right">Won</th><th className="py-2 text-right">Conversion</th><th className="py-2 text-right">Sales</th></tr></thead><tbody>{bySalesperson.map(row=><tr key={row.name} className="border-b last:border-0"><td className="py-3 font-semibold">{row.name}</td><td className="py-3 text-right">{row.quotes}</td><td className="py-3 text-right">{row.wins}</td><td className="py-3 text-right font-semibold text-emerald-700">{row.conversion}%</td><td className="py-3 text-right font-semibold">{currency(row.sales)}</td></tr>)}</tbody></table>{!bySalesperson.length&&<p className="py-8 text-center text-slate-500">No sales data yet.</p>}</div></article><article className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Monthly accepted sales</h2><div className="mt-6 flex h-44 items-end gap-3">{months.map(month=><div key={month.key} className="flex flex-1 flex-col items-center justify-end gap-2"><span className="text-xs font-semibold text-slate-500">{month.value?compactCurrency(month.value):"$0"}</span><div className="w-full rounded-t-lg bg-emerald-600" style={{height:`${Math.max(month.value?12:2,month.value/max*112)}px`}}/><span className="text-xs font-semibold">{month.label}</span></div>)}</div></article></section>}
const currency=(value:number)=>new Intl.NumberFormat("en-NZ",{style:"currency",currency:"NZD",maximumFractionDigits:0}).format(value),compactCurrency=(value:number)=>new Intl.NumberFormat("en-NZ",{style:"currency",currency:"NZD",notation:"compact",maximumFractionDigits:1}).format(value);

type Archived={quotes:{id:number;quoteNumber:string;customerName:string;project:string}[];customers:{id:number;name:string;companyName:string}[];products:{id:number;name:string;category:string}[]};
export function ArchivePanel(){const [data,setData]=useState<Archived>({quotes:[],customers:[],products:[]});async function load(){const r=await fetch("/api/archive");if(r.ok)setData(await r.json())}useEffect(()=>{load()},[]);async function restore(type:"quote"|"customer"|"product",id:number){const r=await fetch("/api/archive",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type,id})});if(r.ok)load()}const groups=[{key:"quote" as const,title:"Jobs and quotes",rows:data.quotes.map(x=>({id:x.id,title:x.quoteNumber,detail:`${x.customerName} · ${x.project}`}))},{key:"customer" as const,title:"Customers",rows:data.customers.map(x=>({id:x.id,title:x.name,detail:x.companyName}))},{key:"product" as const,title:"Products",rows:data.products.map(x=>({id:x.id,title:x.name,detail:x.category}))}];return <div className="space-y-5"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-bold"><Archive className="text-emerald-700"/>Archive and restore</h2><p className="mt-1 text-sm text-slate-500">Archived records stay safe here and can be restored at any time.</p></section>{groups.map(group=><section key={group.key} className="overflow-hidden rounded-2xl border bg-white shadow-sm"><h3 className="border-b px-5 py-4 font-bold">{group.title}</h3>{group.rows.map(row=><div key={row.id} className="flex items-center justify-between gap-4 border-b px-5 py-4 last:border-0"><div><p className="font-semibold">{row.title}</p><p className="text-sm text-slate-500">{row.detail||"No additional details"}</p></div><Button variant="outline" size="sm" onClick={()=>restore(group.key,row.id)}><RotateCcw className="size-4"/>Restore</Button></div>)}{!group.rows.length&&<p className="p-6 text-sm text-slate-500">Nothing archived.</p>}</section>)}</div>}

type Settings={companyName:string;subtitle:string;gstNumber:string;phone:string;email:string;address:string;bankDetails:string;defaultValidityDays:number;depositPercent:number;terms:string;warranty:string;installationExclusions:string;emailSignature:string};
export function SettingsPanel(){const [settings,setSettings]=useState<Settings|null>(null),[saving,setSaving]=useState(false),[message,setMessage]=useState("");useEffect(()=>{fetch("/api/settings").then(r=>r.json()).then(d=>setSettings(d.settings))},[]);if(!settings)return <div className="rounded-2xl border bg-white p-8">Loading company settings…</div>;async function save(e:React.FormEvent){e.preventDefault();setSaving(true);const r=await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});setSaving(false);setMessage(r.ok?"Company settings saved.":"Settings could not be saved.")}const field=(key:keyof Settings,label:string,type="text")=><div className="grid gap-2"><Label>{label}</Label><Input type={type} value={String(settings[key])} onChange={e=>setSettings({...settings,[key]:type==="number"?Number(e.target.value):e.target.value})}/></div>;return <form onSubmit={save} className="space-y-5"><section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="flex items-center gap-2 text-xl font-bold"><Settings2 className="text-emerald-700"/>Company and quotation settings</h2><p className="mt-1 text-sm text-slate-500">These details are used in quotation branding, terms and standard defaults.</p></section><section className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm sm:grid-cols-2">{field("companyName","Company name")}{field("subtitle","Business subtitle")}{field("gstNumber","GST number")}{field("phone","Business phone")}{field("email","Business email","email")}{field("address","Business address")} {field("defaultValidityDays","Default quote validity (days)","number")}{field("depositPercent","Default deposit percentage","number")}<TextSetting label="Bank details" value={settings.bankDetails} onChange={value=>setSettings({...settings,bankDetails:value})}/><TextSetting label="Quotation terms" value={settings.terms} onChange={value=>setSettings({...settings,terms:value})}/><TextSetting label="Warranty information" value={settings.warranty} onChange={value=>setSettings({...settings,warranty:value})}/><TextSetting label="Installation exclusions" value={settings.installationExclusions} onChange={value=>setSettings({...settings,installationExclusions:value})}/><TextSetting label="Email signature" value={settings.emailSignature} onChange={value=>setSettings({...settings,emailSignature:value})}/><div className="sm:col-span-2 flex items-center justify-between"><p className="text-sm font-semibold text-emerald-700">{message}</p><Button disabled={saving}><Save className="size-4"/>{saving?"Saving…":"Save settings"}</Button></div></section></form>}
function TextSetting({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <div className="grid gap-2 sm:col-span-2"><Label>{label}</Label><textarea className="min-h-24 rounded-md border bg-white p-3 text-sm" value={value} onChange={e=>onChange(e.target.value)}/></div>}
