"use client";

import { useEffect, useState } from "react";
import {
  BarChart3, BriefcaseBusiness, Check, ChevronRight, ClipboardCheck,
  FileText, LayoutDashboard, Mail, PackageCheck, Plus, ReceiptText, RefreshCw,
  Search, ShieldCheck, Sparkles, Users, WalletCards, X,
} from "lucide-react";

type Role = "Admin" | "Sales" | "Accounts" | "Operations";
type View = "Dashboard" | "Quotes" | "Customers" | "Invoices" | "Jobs" | "Pick lists";
type QuoteStatus = "Draft" | "Sent" | "Accepted" | "Declined";
type Quote = { id:number; number:string; customer:string; project:string; salesperson:string; service:string; status:QuoteStatus; total:number; validUntil:string; invoice:string };
type Customer = { id:number; name:string; company:string; email:string; phone:string; site:string };
type Job = { id:number; customer:string; project:string; service:string; stage:string; payment:string; date:string };

const seedQuotes: Quote[] = [
  {id:1,number:"RF-2026-1048",customer:"Olivia Martin",project:"Walk-in wardrobe",salesperson:"Mia Chen",service:"Installation",status:"Sent",total:4890,validUntil:"28 Sep 2026",invoice:"—"},
  {id:2,number:"RF-2026-1047",customer:"Harakeke Homes",project:"Three-bedroom fit-out",salesperson:"Noah Patel",service:"Installation",status:"Accepted",total:12850,validUntil:"24 Sep 2026",invoice:"Waiting for payment"},
  {id:3,number:"RF-2026-1046",customer:"Daniel Wilson",project:"Sliding doors & internals",salesperson:"Mia Chen",service:"Delivery",status:"Draft",total:3425,validUntil:"02 Oct 2026",invoice:"—"},
  {id:4,number:"RF-2026-1045",customer:"Sophie Chen",project:"Bedroom wardrobes",salesperson:"Noah Patel",service:"Pick up",status:"Accepted",total:6160,validUntil:"20 Sep 2026",invoice:"Paid 50%"},
];
const seedCustomers: Customer[] = [
  {id:1,name:"Olivia Martin",company:"",email:"olivia@example.test",phone:"021 555 0142",site:"Merivale, Christchurch"},
  {id:2,name:"Aroha Williams",company:"Harakeke Homes",email:"aroha@example.test",phone:"021 555 0188",site:"Rolleston"},
  {id:3,name:"Daniel Wilson",company:"",email:"daniel@example.test",phone:"027 555 0109",site:"Halswell, Christchurch"},
  {id:4,name:"Sophie Chen",company:"",email:"sophie@example.test",phone:"022 555 0124",site:"Lincoln"},
];
const seedJobs: Job[] = [
  {id:1,customer:"Harakeke Homes",project:"Three-bedroom fit-out",service:"Installation",stage:"Site measure booked",payment:"Waiting for payment",date:"22 Sep"},
  {id:2,customer:"Sophie Chen",project:"Bedroom wardrobes",service:"Pick up",stage:"Ready for dispatch",payment:"Paid 50%",date:"19 Sep"},
];

const roleViews: Record<Role, View[]> = {
  Admin:["Dashboard","Quotes","Customers","Invoices","Jobs","Pick lists"],
  Sales:["Dashboard","Quotes","Customers"], Accounts:["Dashboard","Invoices","Customers"],
  Operations:["Dashboard","Jobs","Pick lists"],
};
const money = (n:number) => new Intl.NumberFormat("en-NZ",{style:"currency",currency:"NZD"}).format(n);

export default function DemoApp(){
  const [role,setRole]=useState<Role>("Admin"); const [view,setView]=useState<View>("Dashboard");
  const [quotes,setQuotes]=useState<Quote[]>(seedQuotes); const [customers,setCustomers]=useState<Customer[]>(seedCustomers);
  const [jobs,setJobs]=useState<Job[]>(seedJobs); const [search,setSearch]=useState(""); const [newQuote,setNewQuote]=useState(false);
  const [toast,setToast]=useState(""); const [hydrated,setHydrated]=useState(false);
  useEffect(()=>{try{const v=localStorage.getItem("robeflow-demo-v1");if(v){const d=JSON.parse(v);setQuotes(d.quotes||seedQuotes);setCustomers(d.customers||seedCustomers);setJobs(d.jobs||seedJobs)}}finally{setHydrated(true)}},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem("robeflow-demo-v1",JSON.stringify({quotes,customers,jobs}))},[quotes,customers,jobs,hydrated]);
  function changeRole(next:Role){setRole(next);if(!roleViews[next].includes(view))setView("Dashboard")}
  function notify(message:string){setToast(message);setTimeout(()=>setToast(""),3200)}
  function reset(){setQuotes(seedQuotes);setCustomers(seedCustomers);setJobs(seedJobs);setView("Dashboard");notify("Demo data restored.")}
  const pipeline=quotes.filter(q=>q.status!=="Declined").reduce((s,q)=>s+q.total,0);
  const accepted=quotes.filter(q=>q.status==="Accepted").length;
  const conversion=Math.round((accepted/quotes.length)*100);
  const filtered=quotes.filter(q=>`${q.number} ${q.customer} ${q.project}`.toLowerCase().includes(search.toLowerCase()));
  const navIcon:Record<View,React.ReactNode>={Dashboard:<LayoutDashboard/>,Quotes:<FileText/>,Customers:<Users/>,Invoices:<ReceiptText/>,Jobs:<BriefcaseBusiness/>,"Pick lists":<ClipboardCheck/>};

  return <div className="min-h-screen bg-[#f4f7f9] text-slate-900">
    <header className="border-b border-emerald-100 bg-emerald-950 px-4 py-2 text-center text-xs font-medium text-emerald-50">
      <Sparkles className="mr-1 inline size-3"/> Interactive portfolio demo · All names, records and actions are fictional
    </header>
    <div className="lg:grid lg:min-h-[calc(100vh-33px)] lg:grid-cols-[244px_1fr]">
      <aside className="flex flex-col bg-[#10213d] p-4 text-white lg:min-h-full">
        <div className="flex items-center gap-3 border-b border-white/10 pb-5"><a href="/" aria-label="RobeFlow home" className="grid size-10 place-items-center rounded-xl bg-emerald-400 text-slate-950"><WalletCards className="size-5"/></a><div><h1 className="text-lg font-extrabold tracking-tight">RobeFlow</h1><p className="text-xs text-slate-400">Interactive full-workflow demo</p></div></div>
        <nav className="mt-5 grid grid-cols-3 gap-2 lg:block lg:space-y-1">{roleViews[role].map(item=><button key={item} onClick={()=>setView(item)} className={`flex items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition ${view===item?"bg-emerald-400 text-slate-950":"text-slate-300 hover:bg-white/10 hover:text-white"}`}><span className="[&>svg]:size-4">{navIcon[item]}</span><span>{item}</span></button>)}</nav>
        <div className="mt-auto hidden rounded-2xl border border-white/10 bg-white/5 p-4 lg:block"><p className="text-sm font-bold">Designed & built by Sai</p><p className="mt-1 text-xs leading-5 text-slate-400">Full-stack workflow concept for wardrobe sales and operations.</p><div className="mt-3 flex gap-3"><a className="inline-flex items-center gap-1 text-xs font-bold text-emerald-300 hover:text-emerald-200" href="/">Project overview <ChevronRight className="size-3"/></a><a className="inline-flex items-center gap-1 text-xs font-bold text-emerald-300 hover:text-emerald-200" href="https://sai-quote-manager.saichandreddy.chatgpt.site/staff">Staff login</a></div></div>
      </aside>
      <main className="min-w-0">
        <div className="flex flex-col gap-3 border-b bg-white px-5 py-4 sm:flex-row sm:items-center sm:justify-between lg:px-8">
          <div><p className="text-xs font-bold uppercase tracking-[.16em] text-emerald-700">Demo workspace</p><h2 className="text-xl font-extrabold">{view}</h2></div>
          <div className="flex flex-wrap items-center gap-2"><label className="text-xs font-semibold text-slate-500" htmlFor="role">View as</label><select id="role" value={role} onChange={e=>changeRole(e.target.value as Role)} className="rounded-lg border bg-white px-3 py-2 text-sm font-semibold"><option>Admin</option><option>Sales</option><option>Accounts</option><option>Operations</option></select><button onClick={reset} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-slate-50"><RefreshCw className="size-4"/>Reset demo</button>{(role==="Admin"||role==="Sales")&&<button onClick={()=>setNewQuote(true)} className="inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold text-white hover:bg-emerald-800"><Plus className="size-4"/>New sample quote</button>}</div>
        </div>
        <div className="p-5 lg:p-8">
          {view==="Dashboard"&&<Dashboard pipeline={pipeline} quotes={quotes} customers={customers} accepted={accepted} conversion={conversion} role={role} setView={setView}/>} 
          {view==="Quotes"&&<Quotes quotes={filtered} search={search} setSearch={setSearch} canEdit={role==="Admin"||role==="Sales"} setStatus={(id,status)=>setQuotes(q=>q.map(x=>x.id===id?{...x,status}:x))} email={(id)=>{setQuotes(q=>q.map(x=>x.id===id&&x.status==="Draft"?{...x,status:"Sent"}:x));notify("Quotation email simulated — no real message was sent.")}}/>}
          {view==="Customers"&&<Customers customers={customers}/>} 
          {view==="Invoices"&&<Invoices quotes={quotes.filter(q=>q.status==="Accepted")} setInvoice={(id,invoice)=>setQuotes(q=>q.map(x=>x.id===id?{...x,invoice}:x))} email={()=>notify("Invoice email simulated — no real message was sent.")}/>} 
          {view==="Jobs"&&<Jobs jobs={jobs} setStage={(id,stage)=>setJobs(j=>j.map(x=>x.id===id?{...x,stage}:x))}/>} 
          {view==="Pick lists"&&<PickLists notify={notify}/>} 
        </div>
      </main>
    </div>
    {newQuote&&<NewQuote close={()=>setNewQuote(false)} save={(q,c)=>{setQuotes(x=>[q,...x]);if(!customers.some(x=>x.email===c.email))setCustomers(x=>[c,...x]);setNewQuote(false);setView("Quotes");notify(`${q.number} created in this browser.`)}}/>}
    {toast&&<div className="fixed bottom-5 right-5 z-50 flex max-w-sm items-center gap-3 rounded-xl bg-slate-950 px-4 py-3 text-sm font-semibold text-white shadow-2xl"><Check className="size-4 text-emerald-400"/>{toast}</div>}
  </div>
}

function Dashboard({pipeline,quotes,customers,accepted,conversion,role,setView}:{pipeline:number;quotes:Quote[];customers:Customer[];accepted:number;conversion:number;role:Role;setView:(v:View)=>void}){
  const cards=[{label:"Active pipeline",value:money(pipeline),hint:"Open opportunities",icon:<BarChart3/>},{label:"Total quotes",value:String(quotes.length),hint:"Across all statuses",icon:<FileText/>},{label:"Accepted",value:String(accepted),hint:`${conversion}% conversion rate`,icon:<Check/>},{label:"Customers",value:String(customers.length),hint:"Fictional demo records",icon:<Users/>}];
  return <div className="space-y-6"><section className="overflow-hidden rounded-3xl bg-gradient-to-br from-[#10213d] to-[#17375a] p-6 text-white shadow-sm sm:p-8"><div className="max-w-2xl"><span className="rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-bold text-emerald-300">ROLE: {role.toUpperCase()}</span><h3 className="mt-4 text-3xl font-extrabold tracking-tight">A connected workflow from enquiry to installation.</h3><p className="mt-3 max-w-xl text-sm leading-6 text-slate-300">Switch roles above to see how sales, accounts and operations share one source of truth. Changes are stored only in your browser.</p></div></section><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(c=><article key={c.label} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-slate-500">{c.label}</p><p className="mt-2 text-2xl font-extrabold">{c.value}</p><p className="mt-1 text-xs text-slate-500">{c.hint}</p></div><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700 [&>svg]:size-5">{c.icon}</span></div></article>)}</section><section className="rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h3 className="font-extrabold">Recent activity</h3><p className="text-sm text-slate-500">A snapshot of the fictional sales pipeline.</p></div><button onClick={()=>setView(role==="Accounts"?"Invoices":role==="Operations"?"Jobs":"Quotes")} className="text-sm font-bold text-emerald-700">Open workspace</button></div>{quotes.slice(0,4).map(q=><div key={q.id} className="grid gap-2 border-b px-5 py-4 last:border-0 sm:grid-cols-[150px_1fr_140px_110px] sm:items-center"><b className="text-sm text-emerald-700">{q.number}</b><div><p className="font-semibold">{q.customer}</p><p className="text-xs text-slate-500">{q.project}</p></div><Status value={q.status}/><b className="text-right text-sm">{money(q.total)}</b></div>)}</section></div>
}

function Quotes({quotes,search,setSearch,canEdit,setStatus,email}:{quotes:Quote[];search:string;setSearch:(s:string)=>void;canEdit:boolean;setStatus:(id:number,s:QuoteStatus)=>void;email:(id:number)=>void}){return <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="text-lg font-extrabold">Quotation pipeline</h3><p className="text-sm text-slate-500">Create, send and track customer decisions.</p></div><div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search quotes…" className="rounded-lg border py-2 pl-9 pr-3 text-sm"/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Quote</th><th>Customer</th><th>Salesperson</th><th>Service</th><th>Status</th><th className="text-right">Total</th><th className="p-4 text-right">Action</th></tr></thead><tbody>{quotes.map(q=><tr key={q.id} className="border-t"><td className="p-4 font-bold text-emerald-700">{q.number}<span className="block font-normal text-slate-500">{q.project}</span></td><td className="font-semibold">{q.customer}</td><td>{q.salesperson}</td><td>{q.service}</td><td>{canEdit?<select value={q.status} onChange={e=>setStatus(q.id,e.target.value as QuoteStatus)} className="rounded-lg border px-2 py-1.5 font-semibold"><option>Draft</option><option>Sent</option><option>Accepted</option><option>Declined</option></select>:<Status value={q.status}/>}</td><td className="text-right font-bold">{money(q.total)}</td><td className="p-4 text-right"><button onClick={()=>email(q.id)} className="inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 font-semibold hover:bg-slate-50"><Mail className="size-3.5"/>Send</button></td></tr>)}</tbody></table></div></section>}
function Customers({customers}:{customers:Customer[]}){return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{customers.map(c=><article key={c.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-emerald-100 font-extrabold text-emerald-800">{c.name.split(" ").map(x=>x[0]).join("")}</span><div><h3 className="font-extrabold">{c.name}</h3><p className="text-sm text-slate-500">{c.company||"Residential customer"}</p></div></div><dl className="mt-5 space-y-2 text-sm"><div><dt className="text-xs font-bold uppercase text-slate-400">Email</dt><dd>{c.email}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-400">Phone</dt><dd>{c.phone}</dd></div><div><dt className="text-xs font-bold uppercase text-slate-400">Site</dt><dd>{c.site}</dd></div></dl></article>)}</div>}
function Invoices({quotes,setInvoice,email}:{quotes:Quote[];setInvoice:(id:number,s:string)=>void;email:()=>void}){return <div className="space-y-4">{quotes.map(q=><article key={q.id} className="grid gap-4 rounded-2xl border bg-white p-5 shadow-sm lg:grid-cols-[1fr_180px_190px_auto] lg:items-center"><div><p className="text-sm font-bold text-emerald-700">INV-{q.number.slice(3)}</p><h3 className="font-extrabold">{q.customer} · {q.project}</h3><p className="text-sm text-slate-500">{q.service} · Quote {q.number}</p></div><div><p className="text-xs font-bold uppercase text-slate-400">Invoice total</p><p className="text-lg font-extrabold">{money(q.total)}</p></div><select value={q.invoice} onChange={e=>setInvoice(q.id,e.target.value)} className="rounded-lg border px-3 py-2 text-sm font-semibold"><option>Invoice pending</option><option>Waiting for payment</option><option>Paid 50%</option><option>Paid in full</option><option>On account</option></select><button onClick={email} className="inline-flex items-center justify-center gap-2 rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold text-white"><Mail className="size-4"/>Send invoice</button></article>)}</div>}
function Jobs({jobs,setStage}:{jobs:Job[];setStage:(id:number,s:string)=>void}){return <div className="grid gap-4 lg:grid-cols-2">{jobs.map(j=><article key={j.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-emerald-700">{j.service}</p><h3 className="mt-1 text-lg font-extrabold">{j.customer}</h3><p className="text-sm text-slate-500">{j.project}</p></div><span className="h-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{j.date}</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold uppercase text-slate-400">Workflow<select value={j.stage} onChange={e=>setStage(j.id,e.target.value)} className="mt-1 block w-full rounded-lg border px-3 py-2 text-sm font-semibold normal-case text-slate-900"><option>Site measure booked</option><option>Production</option><option>Ready for dispatch</option><option>Completed</option></select></label><div><p className="text-xs font-bold uppercase text-slate-400">Payment</p><p className="mt-1 flex items-center gap-2 text-sm font-semibold"><ShieldCheck className="size-4 text-emerald-700"/>{j.payment}</p></div></div></article>)}</div>}
function PickLists({notify}:{notify:(s:string)=>void}){const items=["Top panel — white linear","450 mm 6-shelf tower","Hanging rail — silver","Shelf support pack","Wall-mounted shoe rack"];const [checked,setChecked]=useState<string[]>([]);return <section className="mx-auto max-w-4xl rounded-2xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-5"><div><h3 className="text-lg font-extrabold">Consolidated warehouse pick list</h3><p className="text-sm text-slate-500">RF-2026-1045 · Sophie Chen · Pick up</p></div><span className="rounded-full bg-emerald-50 px-3 py-1 text-sm font-bold text-emerald-800">{checked.length}/{items.length} picked</span></div><div className="p-5"><div className="grid grid-cols-[1fr_90px] border-b bg-slate-900 px-4 py-3 text-xs font-bold uppercase text-white"><span>Component</span><span className="text-center">Quantity</span></div>{items.map((item,i)=><label key={item} className="grid cursor-pointer grid-cols-[32px_1fr_90px] items-center border-b px-4 py-4 hover:bg-slate-50"><input type="checkbox" checked={checked.includes(item)} onChange={()=>setChecked(x=>x.includes(item)?x.filter(v=>v!==item):[...x,item])} className="size-4 accent-emerald-700"/><span className={checked.includes(item)?"text-slate-400 line-through":"font-semibold"}>{item}</span><span className="text-center font-bold">{i===0?"2.5":"1"}</span></label>)}<button onClick={()=>notify("Pick list marked ready for dispatch in demo mode.")} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-emerald-700 px-4 py-2.5 text-sm font-bold text-white"><PackageCheck className="size-4"/>Complete pick list</button></div></section>}
function NewQuote({close,save}:{close:()=>void;save:(q:Quote,c:Customer)=>void}){const [name,setName]=useState("");const [email,setEmail]=useState("");const [project,setProject]=useState("");const [total,setTotal]=useState("2500");function submit(e:React.FormEvent){e.preventDefault();const id=Date.now();const number=`RF-2026-${String(id).slice(-4)}`;save({id,number,customer:name,project,salesperson:"Demo user",service:"Installation",status:"Draft",total:Number(total),validUntil:"30 Sep 2026",invoice:"—"},{id,name,company:"",email,phone:"021 555 0100",site:"Christchurch"})}return <div className="fixed inset-0 z-40 grid place-items-center bg-slate-950/55 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Safe demo action</p><h3 className="text-xl font-extrabold">Create a sample quote</h3></div><button type="button" onClick={close} className="rounded-lg p-2 hover:bg-slate-100"><X className="size-5"/></button></div><p className="mt-2 text-sm text-slate-500">This record stays in this browser and can be removed with Reset demo.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Customer name" value={name} set={setName}/><Field label="Customer email" value={email} set={setEmail} type="email"/><div className="sm:col-span-2"><Field label="Project" value={project} set={setProject}/></div><Field label="Quote total (NZD)" value={total} set={setTotal} type="number"/></div><button disabled={!name||!email||!project} className="mt-6 w-full rounded-xl bg-emerald-700 px-4 py-3 font-bold text-white disabled:opacity-40">Create sample quote</button></form></div>}
function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label className="grid gap-1.5 text-sm font-bold">{label}<input required type={type} value={value} onChange={e=>set(e.target.value)} className="rounded-lg border px-3 py-2.5 font-normal"/></label>}
function Status({value}:{value:string}){const cls=value==="Accepted"?"bg-emerald-100 text-emerald-800":value==="Sent"?"bg-blue-100 text-blue-800":value==="Declined"?"bg-rose-100 text-rose-800":"bg-amber-100 text-amber-800";return <span className={`w-fit rounded-full px-2.5 py-1 text-xs font-bold ${cls}`}>{value}</span>}
