import { env } from "cloudflare:workers";
import { eq } from "drizzle-orm";
import { getDb } from "../../../../../db";
import { companySettings,paymentTransactions,quoteActivities,quoteItems,quotes } from "../../../../../db/schema";
import { createInvoicePdf } from "../../../../../lib/invoice-pdf";
import { requireRolesApi } from "../../../../api-auth";
const dummyBank="XYZ Bank\nAccount name: RobeFlow Wardrobes\nAccount number: 00-0000-0000000-00\nReference: Use your invoice number";
function base64(bytes:Uint8Array){let binary="";for(let offset=0;offset<bytes.length;offset+=32768)binary+=String.fromCharCode(...bytes.subarray(offset,offset+32768));return btoa(binary)}
export async function POST(_:Request,context:{params:Promise<{id:string}>}){
 const denied=await requireRolesApi(["Accounts","Staff"]);if(denied)return denied;const id=Number((await context.params).id),db=getDb(),[quote]=await db.select().from(quotes).where(eq(quotes.id,id)).limit(1);if(!quote)return Response.json({error:"Invoice not found."},{status:404});if(!quote.invoiceNumber.trim())return Response.json({error:"Enter the Xero invoice number before sending."},{status:400});if(!quote.email?.trim()||!/^\S+@\S+\.\S+$/.test(quote.email))return Response.json({error:"Add a valid customer email address before sending."},{status:400});
 const quoteLines=await db.select().from(quoteItems).where(eq(quoteItems.quoteId,id)).orderBy(quoteItems.sortOrder),items=[...quoteLines,...(quote.servicePrice>0?[{category:quote.serviceType,systemType:"Service",colour:"",price:quote.servicePrice}]:[])],payments=await db.select().from(paymentTransactions).where(eq(paymentTransactions.quoteId,id)),[settings]=await db.select().from(companySettings).where(eq(companySettings.id,1)).limit(1),token=quote.acceptanceToken||crypto.randomUUID(),bankDetails=settings?.bankDetails.trim()||dummyBank;
 const runtime=env as unknown as {RESEND_API_KEY?:string;QUOTE_EMAIL_FROM?:string;QUOTE_EMAIL_REPLY_TO?:string;PUBLIC_APP_URL?:string},pdf=await createInvoicePdf({...quote,items,payments,bankDetails,companyNameSetting:settings?.companyName||"RobeFlow Wardrobes",companyAddress:settings?.address||"Christchurch, New Zealand",gstNumber:settings?.gstNumber||""}),viewUrl=`${runtime.PUBLIC_APP_URL||"http://localhost:3000"}/invoice/${token}`;if(!runtime.RESEND_API_KEY)return Response.json({error:"Email service is not configured."},{status:503});
 const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${runtime.RESEND_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({from:runtime.QUOTE_EMAIL_FROM||"RobeFlow <onboarding@resend.dev>",to:[quote.email.trim()],reply_to:runtime.QUOTE_EMAIL_REPLY_TO,subject:`Invoice ${quote.invoiceNumber} - ${quote.project}`,html:`<div style="font-family:Arial,sans-serif;color:#172033;line-height:1.6"><h2 style="color:#047857">Your RobeFlow invoice</h2><p>Hi ${quote.customerName.replace(/[<>&]/g,"")},</p><p>Please find invoice <strong>${quote.invoiceNumber.replace(/[<>&]/g,"")}</strong> attached as a PDF.</p><p><a href="${viewUrl}" style="display:inline-block;background:#047857;color:white;padding:12px 18px;border-radius:8px;text-decoration:none;font-weight:bold">View invoice and payment details</a></p><p>You can use the bank details shown on the invoice to pay through your banking app or website.</p><p>Kind regards,<br><strong>RobeFlow Wardrobes</strong></p></div>`,text:`Hi ${quote.customerName},\n\nPlease find invoice ${quote.invoiceNumber} attached as a PDF.\n\nView invoice and payment details: ${viewUrl}\n\nUse the bank details shown on the invoice to pay through your banking app or website.\n\nKind regards,\nRobeFlow Wardrobes`,attachments:[{filename:`${quote.invoiceNumber}.pdf`,content:base64(pdf),content_type:"application/pdf"}]})});const result=await response.json() as {id?:string;message?:string;error?:{message?:string}};if(!response.ok||!result.id)return Response.json({error:result.message||result.error?.message||"The invoice email could not be sent."},{status:502});
 const sentAt=new Date().toISOString(),[updated]=await db.update(quotes).set({invoiceStatus:"Waiting for payment",invoiceSentAt:sentAt,acceptanceToken:token}).where(eq(quotes.id,id)).returning();await db.insert(quoteActivities).values({quoteId:id,action:"Invoice emailed",detail:`${quote.invoiceNumber} sent to ${quote.email}`,actor:"Accounts team"});return Response.json({invoice:updated,viewUrl});
}
