create table if not exists public.custom_field_definitions (
  id bigint generated by default as identity primary key,
  field_key text not null unique,
  label text not null,
  field_type text not null check (field_type in ('text','number','date','boolean','select')),
  options jsonb not null default '[]'::jsonb,
  required boolean not null default false,
  show_new_quote boolean not null default true,
  show_dashboard boolean not null default false,
  show_job_card boolean not null default false,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quote_custom_field_values (
  quote_id bigint not null references public.quotes(id) on delete cascade,
  field_id bigint not null references public.custom_field_definitions(id),
  value text not null default '',
  updated_at timestamptz not null default now(),
  primary key (quote_id, field_id)
);

create index if not exists quote_custom_field_values_quote_id_idx
  on public.quote_custom_field_values(quote_id);

alter table public.custom_field_definitions enable row level security;
alter table public.quote_custom_field_values enable row level security;
