alter table public.quotes
  add column if not exists invoice_due_date date,
  add column if not exists quote_follow_up_sent_at timestamptz,
  add column if not exists invoice_follow_up_sent_at timestamptz,
  add column if not exists customer_response_notified_at timestamptz;

create table if not exists public.additional_invoices (
  id bigint generated by default as identity primary key,
  quote_id bigint not null references public.quotes(id) on delete cascade,
  invoice_number text not null unique,
  description text not null,
  amount numeric(12,2) not null check (amount > 0),
  due_date date not null,
  status text not null default 'Draft' check (status in ('Draft','Sent','Paid','Cancelled')),
  sent_at timestamptz,
  created_by text not null default 'RobeFlow',
  created_at timestamptz not null default now()
);

alter table public.additional_invoices enable row level security;
drop policy if exists staff_access on public.additional_invoices;
create policy staff_access on public.additional_invoices for all to authenticated
using (public.is_approved_staff()) with check (public.is_approved_staff());
grant select, insert, update, delete on public.additional_invoices to authenticated;
grant usage, select on all sequences in schema public to authenticated;

notify pgrst, 'reload schema';
