import { and,eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { jobScheduleEvents,pickListItems,quoteActivities,quoteItems,quotes } from "../../../../db/schema";
import { accessoryParts,iRobeParts } from "../../../../lib/pick-list-catalog";
import { requireRolesApi } from "../../../api-auth";

type MatrixLine={category:string;systemType:string;designSelection:string;quantity:number};
type StoredLine={areaName:string;productName:string;quantity:number;notes:string};
type MatrixRow={name:string;areas:Record<string,number>;total:number};
function buildMatrix(lines:MatrixLine[],stored:StoredLine[]){const areas=[...new Set(lines.map(line=>String(line.category||"Unspecified area")))],manualAreas=new Set(lines.filter(line=>line.designSelection==="Custom design"||line.systemType==="Cabinet System").map(line=>line.category)),components=new Map<string,MatrixRow>(),hardware=new Map<string,number>();for(const line of lines){const qty=Math.max(1,Number(line.quantity)||1),parts=line.systemType==="I-Robe"?iRobeParts(line.designSelection,qty):line.systemType==="Accessories"?accessoryParts(line.designSelection,qty):[];for(const part of parts){if(part.group==="I-Robe hardware"){hardware.set(part.name,(hardware.get(part.name)||0)+Number(part.qty));continue}const row=components.get(part.name)||{name:part.name,areas:{},total:0};row.areas[line.category]=(row.areas[line.category]||0)+Number(part.qty);row.total+=Number(part.qty);components.set(part.name,row)}}for(const item of stored){if(item.notes===AUTO_IROBE_HARDWARE_NOTE||item.notes===AUTO_HARDWARE_NOTE){hardware.set(item.productName,(hardware.get(item.productName)||0)+Number(item.quantity));continue}const itemAreas=String(item.areaName||"Other").split(",").map(value=>value.trim()).filter(Boolean),editableAreas=itemAreas.filter(area=>manualAreas.has(area));if(!editableAreas.length)continue;const row=components.get(item.productName)||{name:item.productName,areas:{},total:0};for(const area of editableAreas){if(!areas.includes(area))areas.push(area);row.areas[area]=(row.areas[area]||0)+Number(item.quantity);row.total+=Number(item.quantity)}components.set(item.productName,row)}return{areas,components:[...components.values()],hardware:[...hardware].map(([name,total])=>({name,total}))}}

export async function GET(_:Request,context:{params:Promise<{id:string}>}){const denied=await requireRolesApi(["Accounts","Operations","Staff"]);if(denied)return denied;const id=Number((await context.params).id),db=getDb(),[job]=await db.select().from(quotes).where(eq(quotes.id,id)).limit(1);if(!job)return Response.json({error:"Job not found."},{status:404});let items=await db.select().from(pickListItems).where(eq(pickListItems.quoteId,id)).orderBy(pickListItems.sortOrder);const hasIRobeComponents=items.some(item=>["2.4m Top Support","2.4m Back Support","1800 Side","1200 Side","1200 Shelf","550 Shelf","400 Shelf","1200 Hanging Bar","550 Hanging Bar","400 Hanging Bar","Drawers (400)","Drawers (550)"].includes(item.productName)),hasIRobeHardware=items.some(item=>item.notes===AUTO_IROBE_HARDWARE_NOTE),hasCabinetComponents=items.some(item=>/^(1000|900|800|700|600|500|450) (Module|Shelf)$/.test(item.productName)),hasCabinetHardware=items.some(item=>item.notes===AUTO_HARDWARE_NOTE);if(hasIRobeComponents&&!hasIRobeHardware)await recalculateIRobeHardware(db,id);if(hasCabinetComponents&&!hasCabinetHardware)await recalculateCabinetHardware(db,id);if((hasIRobeComponents&&!hasIRobeHardware)||(hasCabinetComponents&&!hasCabinetHardware))items=await db.select().from(pickListItems).where(eq(pickListItems.quoteId,id)).orderBy(pickListItems.sortOrder);const lines=await db.select().from(quoteItems).where(eq(quoteItems.quoteId,id)),schedule=await db.select().from(jobScheduleEvents).where(eq(jobScheduleEvents.quoteId,id)),installation=schedule.find(event=>event.eventType==="Installation"&&event.status!=="Cancelled")??null,matrix=buildMatrix(lines,items),manualAreas=lines.filter(line=>line.designSelection==="Custom design"||line.systemType==="Cabinet System").map(line=>line.category);return Response.json({job,items,lines,matrix,manualAreas,installation});}

export async function POST(request:Request,context:{params:Promise<{id:string}>}){const denied=await requireRolesApi(["Operations","Staff"]);if(denied)return denied;const id=Number((await context.params).id),body=await request.json().catch(()=>({})) as {action?:string;productName?:string;sku?:string;quantity?:number;unitCost?:number;areaName?:string;notes?:string;items?:{productName?:string;sku?:string;quantity?:number;unitCost?:number;areaName?:string;notes?:string}[]},db=getDb(),[job]=await db.select().from(quotes).where(eq(quotes.id,id)).limit(1);if(!job)return Response.json({error:"Job not found."},{status:404});
 if(body.action==="manual-batch"){const additions=(body.items??[]).filter(item=>item.productName?.trim()&&Number(item.quantity)>0);if(!additions.length)return Response.json({error:"Enter at least one component quantity."},{status:400});for(const addition of additions)await upsertManual(db,id,{productName:addition.productName!.trim(),sku:addition.sku?.trim()||"",quantity:Number(addition.quantity),unitCost:Math.max(0,Number(addition.unitCost)||0),areaName:addition.areaName?.trim()||"Custom / Cabinet design",notes:addition.notes?.trim()||""});await recalculateCabinetHardware(db,id);await db.update(quotes).set({pickListStatus:"In progress"}).where(eq(quotes.id,id));await db.insert(quoteActivities).values({quoteId:id,action:"Pick-list components added",detail:`${additions.length} component quantities entered; linked hardware recalculated`,actor:"Warehouse team"});return Response.json({items:await db.select().from(pickListItems).where(eq(pickListItems.quoteId,id)).orderBy(pickListItems.sortOrder)},{status:201})}
 if(body.action==="manual-cell"){const name=body.productName?.trim(),area=body.areaName?.trim(),quantity=Math.max(0,Number(body.quantity)||0);if(!name||!area)return Response.json({error:"Component and area are required."},{status:400});const existing=await db.select().from(pickListItems).where(eq(pickListItems.quoteId,id)),matches=existing.filter(item=>item.productName.toLowerCase()===name.toLowerCase()&&item.areaName===area&&item.notes!==AUTO_HARDWARE_NOTE&&item.notes!==AUTO_IROBE_HARDWARE_NOTE);for(const match of matches)await db.delete(pickListItems).where(eq(pickListItems.id,match.id));if(quantity>0)await db.insert(pickListItems).values({quoteId:id,areaName:area,productName:name,sku:body.sku?.trim()||"",quantity,unitCost:Math.max(0,Number(body.unitCost)||0),notes:body.notes?.trim()||"Manual sheet entry",sortOrder:999});await recalculateCabinetHardware(db,id);await db.update(quotes).set({pickListStatus:"In progress"}).where(eq(quotes.id,id));return Response.json({success:true});}
 if(body.action==="manual"){if(!body.productName?.trim()||!Number.isFinite(Number(body.quantity))||Number(body.quantity)<=0)return Response.json({error:"Enter a product and quantity."},{status:400});const item=await upsertManual(db,id,{productName:body.productName.trim(),sku:body.sku?.trim()||"",quantity:Number(body.quantity),unitCost:Math.max(0,Number(body.unitCost)||0),areaName:body.areaName?.trim()||"Custom design",notes:body.notes?.trim()||""});await recalculateCabinetHardware(db,id);await db.update(quotes).set({pickListStatus:"In progress"}).where(eq(quotes.id,id));return Response.json({item},{status:201})}
 const existing=await db.select().from(pickListItems).where(eq(pickListItems.quoteId,id));if(existing.length&&!body.action?.includes("regenerate"))return Response.json({error:"A pick list already exists. Use regenerate to replace it."},{status:409});
 const quoteLines=await db.select().from(quoteItems).where(eq(quoteItems.quoteId,id)).orderBy(quoteItems.sortOrder);await db.delete(pickListItems).where(eq(pickListItems.quoteId,id));let sortOrder=0;const values:{quoteId:number;areaName:string;productName:string;sku:string;quantity:number;unitCost:number;notes:string;sortOrder:number}[]=[];
 for(const line of quoteLines){const qty=Math.max(1,Number(line.quantity)||1);let parts=line.systemType==="I-Robe"?iRobeParts(line.designSelection,qty):line.systemType==="Accessories"?accessoryParts(line.designSelection,qty):[];if(!parts.length&&line.designSelection!=="Custom design")parts=[{name:`${line.systemType}: ${line.designSelection||line.description||"Item"}`,qty,unitCost:Number(line.unitPrice)||0}];for(const part of parts)values.push({quoteId:id,areaName:line.category,productName:part.name,sku:part.sku||"",quantity:part.qty,unitCost:part.unitCost,notes:line.colour?`Colour: ${line.colour}${line.hardwareColour?` · Hardware: ${line.hardwareColour}`:""}`:"",sortOrder:sortOrder++})}
 const consolidated=consolidate(values);if(consolidated.length)await db.insert(pickListItems).values(consolidated);await recalculateIRobeHardware(db,id);const [updated]=await db.update(quotes).set({pickListStatus:"In progress",pickedBy:"",pickedAt:null}).where(eq(quotes.id,id)).returning();await db.insert(quoteActivities).values({quoteId:id,action:existing.length?"Pick list regenerated":"Pick list created",detail:`${consolidated.length} consolidated warehouse lines plus linked hardware`,actor:"Dispatch team"});return Response.json({job:updated,items:await db.select().from(pickListItems).where(eq(pickListItems.quoteId,id)).orderBy(pickListItems.sortOrder),manualAreas:quoteLines.filter(line=>line.designSelection==="Custom design"||line.systemType==="Cabinet System").map(line=>line.category)});
}

function mergeAreas(current:string,next:string){const areas=new Set([...current.split(",").map(x=>x.trim()),...next.split(",").map(x=>x.trim())].filter(Boolean));return [...areas].join(", ")}
async function upsertManual(db:ReturnType<typeof getDb>,quoteId:number,value:{productName:string;sku:string;quantity:number;unitCost:number;areaName:string;notes:string}){const existing=await db.select().from(pickListItems).where(eq(pickListItems.quoteId,quoteId)),match=existing.find(item=>item.productName.toLowerCase()===value.productName.toLowerCase()&&item.sku===value.sku&&item.unitCost===value.unitCost&&item.notes===value.notes);if(match){const [item]=await db.update(pickListItems).set({quantity:match.quantity+value.quantity,areaName:mergeAreas(match.areaName,value.areaName)}).where(eq(pickListItems.id,match.id)).returning();return item}const [item]=await db.insert(pickListItems).values({quoteId,areaName:value.areaName,productName:value.productName,sku:value.sku,quantity:value.quantity,unitCost:value.unitCost,notes:value.notes,sortOrder:999}).returning();return item}
const AUTO_HARDWARE_NOTE="Automatically calculated from Cabinet System components";
const AUTO_IROBE_HARDWARE_NOTE="Automatically calculated from I-Robe components";
async function recalculateCabinetHardware(db:ReturnType<typeof getDb>,quoteId:number){const all=await db.select().from(pickListItems).where(eq(pickListItems.quoteId,quoteId)),source=all.filter(item=>item.notes!==AUTO_HARDWARE_NOTE),sum=(test:(name:string)=>boolean)=>source.filter(item=>test(item.productName)).reduce((total,item)=>total+Number(item.quantity),0),modules=sum(name=>/^(1000|900|800|700|600|500|450) Module$/.test(name)),woodScrewModules=sum(name=>/^(1000|800|700|600|500|450) Module$/.test(name)),shelves=sum(name=>/^(1000|900|800|700|600|500|450) Shelf$/.test(name)),standardBars=sum(name=>name==="Hanging Bar Standard"),cutDowns=sum(name=>name==="Module cut down"),areas=source.filter(item=>/^(1000|900|800|700|600|500|450) Module$/.test(item.productName)).map(item=>item.areaName).reduce((value,area)=>mergeAreas(value,area),"");await Promise.all(all.filter(item=>item.notes===AUTO_HARDWARE_NOTE).map(item=>db.delete(pickListItems).where(eq(pickListItems.id,item.id))));const hardware=[{name:"Metal cams",qty:modules*20},{name:"Cam dowels",qty:modules*20},{name:"Cam covers (plastic)",qty:modules*20},{name:"Shelf screws",qty:shelves*4},{name:"Shelf cams (plastic)",qty:shelves*4},{name:"Hanging-bar brackets",qty:standardBars*2},{name:"Hanging-bar screws",qty:standardBars*4},{name:"Wood screws (45mm)",qty:woodScrewModules*8},{name:"Cover caps (stickers)",qty:cutDowns*4},{name:"Instructions",qty:modules+shelves+standardBars>0?1:0}].filter(item=>item.qty>0);if(hardware.length)await db.insert(pickListItems).values(hardware.map((item,index)=>({quoteId,areaName:areas||"Cabinet System",productName:item.name,sku:"",quantity:item.qty,unitCost:0,checked:false,notes:AUTO_HARDWARE_NOTE,sortOrder:2000+index})))}
async function recalculateIRobeHardware(db:ReturnType<typeof getDb>,quoteId:number){const all=await db.select().from(pickListItems).where(eq(pickListItems.quoteId,quoteId)),source=all.filter(item=>item.notes!==AUTO_IROBE_HARDWARE_NOTE),sum=(names:string[])=>source.filter(item=>names.includes(item.productName)).reduce((total,item)=>total+Number(item.quantity),0),shelves=sum(["1200 Shelf","675 Shelf","550 Shelf","400 Shelf"]),bars=sum(["1200 Hanging Bar","550 Hanging Bar","400 Hanging Bar"]),drawer400=sum(["Drawers (400)"]),drawer550=sum(["Drawers (550)"]),backSupports=sum(["2.4m Back Support"]),sides1800=sum(["1800 Side"]),areas=source.filter(item=>["2.4m Top Support","2.4m Back Support","1800 Side","1200 Side","1200 Shelf","550 Shelf","400 Shelf"].includes(item.productName)).map(item=>item.areaName).reduce((value,area)=>mergeAreas(value,area),"");await Promise.all(all.filter(item=>item.notes===AUTO_IROBE_HARDWARE_NOTE).map(item=>db.delete(pickListItems).where(eq(pickListItems.id,item.id))));const hardware=[{name:"Shelf cams",qty:shelves*4},{name:"Shelf screws",qty:shelves*4},{name:"Hanging-bar brackets",qty:bars*2},{name:"Hanging-bar screws",qty:bars*4},{name:"8G x 32mm screws",qty:drawer400*4+drawer550*12},{name:"8G x 50mm screws",qty:backSupports*16+sides1800*8},{name:"Instructions",qty:shelves+bars+drawer400+drawer550>0?1:0}].filter(item=>item.qty>0);if(hardware.length)await db.insert(pickListItems).values(hardware.map((item,index)=>({quoteId,areaName:areas||"I-Robe",productName:item.name,sku:"",quantity:item.qty,unitCost:0,checked:false,notes:AUTO_IROBE_HARDWARE_NOTE,sortOrder:3000+index})))}
function consolidate(values:{quoteId:number;areaName:string;productName:string;sku:string;quantity:number;unitCost:number;notes:string;sortOrder:number}[]){const grouped=new Map<string,(typeof values)[number]>();for(const value of values){const key=[value.productName.toLowerCase(),value.sku,value.unitCost,value.notes].join("|");const found=grouped.get(key);if(found){found.quantity+=value.quantity;found.areaName=mergeAreas(found.areaName,value.areaName)}else grouped.set(key,{...value})}return [...grouped.values()].map((value,index)=>({...value,sortOrder:index}))}

export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){const denied=await requireRolesApi(["Operations","Staff"]);if(denied)return denied;const quoteId=Number((await context.params).id),body=await request.json() as {itemId?:number;checked?:boolean;quantity?:number;notes?:string;pickedBy?:string},db=getDb();if(!body.itemId)return Response.json({error:"Pick-list item is required."},{status:400});const changes:{checked?:boolean;quantity?:number;notes?:string}={};if(body.checked!==undefined)changes.checked=body.checked;if(body.quantity!==undefined&&Number(body.quantity)>0)changes.quantity=Number(body.quantity);if(body.notes!==undefined)changes.notes=body.notes.trim();let [item]=await db.update(pickListItems).set(changes).where(and(eq(pickListItems.id,body.itemId),eq(pickListItems.quoteId,quoteId))).returning();if(!item)return Response.json({error:"Pick-list item not found."},{status:404});if(body.quantity!==undefined&&item.notes!==AUTO_HARDWARE_NOTE){await recalculateCabinetHardware(db,quoteId);[item]=await db.select().from(pickListItems).where(eq(pickListItems.id,body.itemId)).limit(1)}const all=await db.select().from(pickListItems).where(eq(pickListItems.quoteId,quoteId)),complete=all.length>0&&all.every(x=>x.checked),[job]=await db.update(quotes).set({pickListStatus:complete?"Picked":"In progress",pickedBy:complete?(body.pickedBy?.trim()||"Warehouse team"):"",pickedAt:complete?new Date().toISOString():null}).where(eq(quotes.id,quoteId)).returning();if(complete)await db.insert(quoteActivities).values({quoteId,action:"Picking completed",detail:`${all.length} lines checked`,actor:job.pickedBy});return Response.json({item,items:all,job});}

export async function DELETE(request:Request,context:{params:Promise<{id:string}>}){const denied=await requireRolesApi(["Operations","Staff"]);if(denied)return denied;const quoteId=Number((await context.params).id),body=await request.json() as {itemId?:number};if(!body.itemId)return Response.json({error:"Pick-list item is required."},{status:400});const db=getDb(),[item]=await db.select().from(pickListItems).where(and(eq(pickListItems.id,body.itemId),eq(pickListItems.quoteId,quoteId))).limit(1);await db.delete(pickListItems).where(and(eq(pickListItems.id,body.itemId),eq(pickListItems.quoteId,quoteId)));if(item&&item.notes!==AUTO_HARDWARE_NOTE)await recalculateCabinetHardware(db,quoteId);return Response.json({success:true});}
